[package]
name = "uniffi-bindgen-cli"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "uniffi-bindgen"
path = "src/main.rs"

[dependencies]
uniffi = { version = "0.27", features = ["cli"] }
