[package]
name = "pallet-bitcoin-fissions"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
publish = false

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
argon-primitives = { workspace = true, features = ["bitcoin"] }
polkadot-sdk = { workspace = true, features = ["frame-support", "frame-system", "sp-runtime", "sp-arithmetic"] }
pallet-prelude = { workspace = true, default-features = false }

[dev-dependencies]
polkadot-sdk = { workspace = true, features = ["pallet-balances", "sp-io", "sp-arithmetic"], default-features = true }
pallet-prelude = { workspace = true, features = ["test"], default-features = true }

[features]
default = [ "std" ]
std = [
	"argon-primitives/bitcoin",
	"argon-primitives/std",
	"codec/std",
	"pallet-prelude/std",
	"polkadot-sdk/std",
	"scale-info/std",
]
runtime-benchmarks = [
	"argon-primitives/runtime-benchmarks",
	"pallet-prelude/runtime-benchmarks",
	"polkadot-sdk/frame-benchmarking",
	"polkadot-sdk/runtime-benchmarks",
]
try-runtime = [ "polkadot-sdk/try-runtime" ]
