[package]
name = "ulx-primitives"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.76", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.4", default-features = false, features = ["derive", "max-encoded-len"] }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false }
scale-info = { version = "2.10", default-features = false, features = ["derive"] }
sp-runtime = { version = "24.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
sp-inherents = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
sp-api = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
sp-application-crypto = { version = "23.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
sp-debug-derive = { version = "8.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
sp-core = { version = "21.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
sp-std = { version = "8.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
sp-core-hashing = { version = "9.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
thiserror = { version = "1.0", optional = true }
impl-trait-for-tuples = "0.2.2"
napi-derive = { version = "2.14", optional = true }
napi = { version = "2.14", optional = true }
rsntp = { version = "4.0", optional = true }
hex = { version = "0.4", optional = true }
clap = { version = "4.5.1", optional = true, features = ["derive"] }

[dev-dependencies]
chrono = "0.4"
tokio = { version = "1.35", features = ["full"] }

[features]
default = ["std"]
std = [
    "async-trait",
    "codec/std",
    "codec/derive",
    "scale-info/std",
    "scale-info/derive",
    "serde/std",
    "serde_json/std",
    "sp-api/std",
    "sp-application-crypto/std",
    "sp-debug-derive/std",
    "sp-core/std",
    "sp-core-hashing/std",
    "sp-inherents/std",
    "sp-runtime/std",
    "clap",
    "hex",
    "sp-std/std",
    "rsntp",
    "thiserror",
    "frame-support/std",
]
fast-runtime = [
    "sp-debug-derive/force-debug",
]
napi = [
    "napi/napi9",
    "napi/serde-json",
    "napi-derive/type-def",
]