[package]
name = "ulx-primitives"
version = "0.0.1"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.73", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
serde = { version = "1.0", features = ["derive"], default-features = false, optional = true }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
sp-runtime = { version = "24.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
sp-inherents = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
sp-api = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
sp-application-crypto = { version = "23.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
sp-core = { version = "21.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
sp-std = { version = "8.0.0", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
frame-support = { version = "4.0.0-dev", default-features = false,  git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
thiserror = { version ="1.0", optional = true }

[features]
default = ["std"]
std = [
  "async-trait",
  "codec/std",
  "scale-info/std",
  "serde/std",
  "sp-api/std",
  "sp-application-crypto/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-runtime/std",
  "sp-std/std",
  "thiserror",
  "frame-support/std",
]

serde = [
  "dep:serde",
  "scale-info/serde",
  "sp-application-crypto/serde",
  "sp-runtime/serde",
]
