[package]
name = "ulx-primitives"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true, optional = true }
codec = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
scale-info = { workspace = true }
sp-runtime = { workspace = true }
sp-inherents = { workspace = true }
sp-api = { workspace = true }
sp-application-crypto = { workspace = true }
sp-debug-derive = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-crypto-hashing = { workspace = true }
frame-support-procedural = { workspace = true }
frame-support = { workspace = true }
thiserror = { workspace = true, optional = true }
impl-trait-for-tuples = { workspace = true }
napi-derive = { workspace = true, optional = true }
napi = { workspace = true, optional = true }
rsntp = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
uniffi = { workspace = true, optional = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[dev-dependencies]
chrono = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[features]
default = ["std"]
std = [
    "async-trait",
    "codec/std",
    "codec/derive",
    "scale-info/std",
    "scale-info/derive",
    "serde/std",
    "serde_json/std",
    "sp-api/std",
    "sp-application-crypto/std",
    "sp-application-crypto/full_crypto",
    "sp-debug-derive/std",
    "sp-core/std",
    "sp-core/full_crypto",
    "sp-crypto-hashing/std",
    "sp-inherents/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-support/std",
    "frame-support-procedural/std",
    "thiserror",
    "clap",
    "hex",
    "rsntp",
]
fast-runtime = [
    "sp-debug-derive/force-debug",
]
napi = [
    "napi/napi9",
    "napi/serde-json",
    "napi-derive/type-def",
]
uniffi = [
    "dep:uniffi"
]