[package]
name = "ulx-primitives"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { version = "0.1.76", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.4", default-features = false, features = ["derive", "max-encoded-len"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
scale-info = { version = "2.10", default-features = false, features = ["derive"] }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-inherents = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-api = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-application-crypto = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-debug-derive = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-core = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-std = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-crypto-hashing = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
frame-support-procedural = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
frame-support = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
thiserror = { version = "1.0", optional = true }
impl-trait-for-tuples = "0.2.2"
napi-derive = { version = "2.16", optional = true }
napi = { version = "2.16", optional = true }
rsntp = { version = "4.0", optional = true }
hex = { version = "0.4", optional = true }
clap = { version = "4.5.1", optional = true, features = ["derive"] }
uniffi = { version = "0.26.1", optional = true }
primitive-types = { version = "0.12.0", default-features = false, features = ["codec", "scale-info"] }
bounded-collections = { version = "0.2.0", default-features = false }

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[dev-dependencies]
chrono = "0.4"
tokio = { version = "1.35", features = ["full"] }

[features]
default = ["std"]
std = [
    "async-trait",
    "codec/std",
    "codec/derive",
    "scale-info/std",
    "scale-info/derive",
    "serde/std",
    "serde_json/std",
    "bounded-collections/std",
    "sp-api/std",
    "sp-application-crypto/std",
    "sp-application-crypto/full_crypto",
    "sp-debug-derive/std",
    "primitive-types/byteorder",
    "primitive-types/rustc-hex",
    "primitive-types/serde",
    "primitive-types/std",
    "sp-core/std",
    "sp-core/full_crypto",
    "sp-crypto-hashing/std",
    "sp-inherents/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-support/std",
    "frame-support-procedural/std",
    "thiserror",
    "clap",
    "hex",
    "rsntp",
]
fast-runtime = [
    "sp-debug-derive/force-debug",
]
napi = [
    "napi/napi9",
    "napi/serde-json",
    "napi-derive/type-def",
]
uniffi = [
    "codec/std",
    "codec/derive",
    "scale-info/std",
    "scale-info/derive",
    "serde/std",
    "serde_json/std",
    "bounded-collections/std",
    "sp-api/std",
    "async-trait",
    "sp-debug-derive/std",
    "primitive-types/byteorder",
    "primitive-types/rustc-hex",
    "primitive-types/serde",
    "sp-application-crypto/full_crypto",
    "sp-application-crypto/serde",
    "sp-core/serde",
    "sp-core/full_crypto",
    "dep:uniffi",
    "thiserror",
    "hex",
    "rsntp",
]