[package]
name = "ulx-notary"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true

[profile.dev.package.sqlx-macros]
opt-level = 3

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = { version = "1" }
futures = { version = "0.3" }
getrandom = { version = "0.2" }
parking_lot = { version = "0.12" }
async-trait = { version = "0.1" }
codec = { package = "parity-scale-codec", version = "3.6", features = ["derive", "max-encoded-len"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value", "arbitrary_precision"] }
scale-info = { version = "2.10" }
thiserror = { version = "1.0" }
subxt = { version = "0.35" }
subxt-signer = { version = "0.35", features = ["default"] }
tokio = { version = "1.35", features = ["rt", "sync", "time"] }
hex = { version = "0.4" }
jsonrpsee = { version = "0.22", features = ["server", "http-client", "ws-client", "macros", "client-ws-transport-native-tls"] }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-core = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0", features = ["serde"] }
sc-utils = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sc-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
binary-merkle-tree = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "macros", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.4", features = ["derive", "cargo", "env"] }
rpassword = { version = "7.3" }

ulixee-client = { path = "../client" }
ulx-notary-audit = { path = "audit" }
ulx-primitives = { path = "../primitives" }
ulx-notary-apis = { path = "apis" }
url = "2.5.0"

[dev-dependencies]
frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.9.0" }
ulx-testing = { path = "../testing" }

[build-dependencies]
patch-crate = "0.1.9"

[features]
fast-runtime = ["ulx-primitives/fast-runtime"]
