[package]
name = "argon-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
smallvec = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }

polkadot-sdk.workspace = true

polkadot-sdk.features = [
    "frame-support",
    "frame-system",
    "frame-executive",
    "sp-api",
    "sp-core",
    "sp-runtime",
    "sp-block-builder",
    "sp-arithmetic",
    "sp-inherents",
    "sp-offchain",
    "sp-session",
    "sp-transaction-pool",
    "sp-version",
    "sp-genesis-builder",
    "sp-consensus-grandpa",
    "frame-system-rpc-runtime-api",
    "frame-metadata-hash-extension",
    "pallet-authorship",
    "pallet-balances",
    "pallet-sudo",
    "pallet-offences",
    "pallet-grandpa",
    "pallet-multisig",
    "pallet-timestamp",
    "pallet-proxy",
    "pallet-tx-pause",
    "pallet-utility",
    "pallet-transaction-payment",
    "pallet-transaction-payment-rpc-runtime-api",
]
sp-debug-derive = { workspace = true, features = ["force-debug"], default-features = false }

pallet-token-gateway = { workspace = true }
pallet-ismp = { workspace = true, features = ["unsigned"] }
pallet-ismp-runtime-api = { workspace = true }
pallet-hyperbridge = { workspace = true }
ismp-grandpa = { workspace = true }
ismp = { workspace = true }
anyhow = { workspace = true, default-features = false }


# Local Dependencies
pallet-bitcoin-utxos = { workspace = true }
pallet-block-seal = { workspace = true }
pallet-block-seal-spec = { workspace = true }
pallet-block-rewards = { workspace = true }
pallet-bitcoin-locks = { workspace = true }
pallet-chain-transfer = { workspace = true }
pallet-digests = { workspace = true }
pallet-domains = { workspace = true }
pallet-notebook = { workspace = true }
pallet-notaries = { workspace = true }
pallet-liquidity-pools = { workspace = true }
pallet-mining-slot = { workspace = true }
pallet-price-index = { workspace = true }
pallet-ticks = { workspace = true }
pallet-mint = { workspace = true }
pallet-vaults = { workspace = true }
argon-primitives = { workspace = true }
argon-runtime-common = { workspace = true, default-features = false }

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
	"anyhow/std",
	"argon-primitives/std",
	"argon-runtime-common/std",
	"codec/std",
	"ismp-grandpa/std",
	"ismp/std",
	"log/std",
	"pallet-bitcoin-locks/std",
	"pallet-bitcoin-utxos/std",
	"pallet-block-rewards/std",
	"pallet-block-seal-spec/std",
	"pallet-block-seal/std",
	"pallet-chain-transfer/std",
	"pallet-digests/std",
	"pallet-domains/std",
	"pallet-hyperbridge/std",
	"pallet-ismp-runtime-api/std",
	"pallet-ismp/std",
	"pallet-liquidity-pools/std",
	"pallet-mining-slot/std",
	"pallet-mint/std",
	"pallet-notaries/std",
	"pallet-notebook/std",
	"pallet-price-index/std",
	"pallet-ticks/std",
	"pallet-token-gateway/std",
	"pallet-vaults/std",
	"polkadot-sdk/std",
	"scale-info/std",
	"serde_json/std",
	"sp-debug-derive/force-debug",
	"sp-debug-derive/std",
	"substrate-wasm-builder",
]
runtime-benchmarks = [
	"argon-runtime-common/runtime-benchmarks",
	"ismp-grandpa/runtime-benchmarks",
	"pallet-bitcoin-locks/runtime-benchmarks",
	"pallet-bitcoin-utxos/runtime-benchmarks",
	"pallet-block-rewards/runtime-benchmarks",
	"pallet-block-seal-spec/runtime-benchmarks",
	"pallet-block-seal/runtime-benchmarks",
	"pallet-chain-transfer/runtime-benchmarks",
	"pallet-digests/runtime-benchmarks",
	"pallet-domains/runtime-benchmarks",
	"pallet-ismp/runtime-benchmarks",
	"pallet-liquidity-pools/runtime-benchmarks",
	"pallet-mining-slot/runtime-benchmarks",
	"pallet-mint/runtime-benchmarks",
	"pallet-notaries/runtime-benchmarks",
	"pallet-notebook/runtime-benchmarks",
	"pallet-price-index/runtime-benchmarks",
	"pallet-ticks/runtime-benchmarks",
	"pallet-token-gateway/runtime-benchmarks",
	"pallet-vaults/runtime-benchmarks",
	"polkadot-sdk/runtime-benchmarks",
]
try-runtime = [
	"argon-runtime-common/try-runtime",
	"ismp-grandpa/try-runtime",
	"pallet-bitcoin-locks/try-runtime",
	"pallet-bitcoin-utxos/try-runtime",
	"pallet-block-rewards/try-runtime",
	"pallet-block-seal-spec/try-runtime",
	"pallet-block-seal/try-runtime",
	"pallet-chain-transfer/try-runtime",
	"pallet-digests/try-runtime",
	"pallet-domains/try-runtime",
	"pallet-hyperbridge/try-runtime",
	"pallet-ismp/try-runtime",
	"pallet-liquidity-pools/try-runtime",
	"pallet-mining-slot/try-runtime",
	"pallet-mint/try-runtime",
	"pallet-notaries/try-runtime",
	"pallet-notebook/try-runtime",
	"pallet-price-index/try-runtime",
	"pallet-ticks/try-runtime",
	"pallet-token-gateway/try-runtime",
	"pallet-vaults/try-runtime",
	"polkadot-sdk/try-runtime",
]

# Enable the metadata hash generation.
#
# This is hidden behind a feature because it increases the compile time.
# The wasm binary needs to be compiled twice, once to fetch the metadata,
# generate the metadata hash and then a second time with the
# `RUNTIME_METADATA_HASH` environment variable set for the `CheckMetadataHash`
# extension.
metadata-hash = [ "substrate-wasm-builder/metadata-hash" ]
on-chain-release-build = [ "metadata-hash" ]
