# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      # Allows cargo fmt to modify the source code prior to the commit
      - id: format
        name: Format code with cargo fmt + zepter
        args: [ "make", "format" ]
        entry: cargo
        language: system
        types: [ rust ]
        pass_filenames: false
        stages: [ commit, push ]
      - id: lint
        name: Run clippy
        args: [ "make", "lint" ]
        entry: cargo
        language: system
        types: [ rust ]
        pass_filenames: false
        stages: [ push ]
