# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [ pre-commit, pre-push ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      # Allows cargo fmt to modify the source code prior to the commit
      - id: format
        name: Format code with cargo fmt + zepter
        args: [ "make", "format" ]
        entry: cargo
        language: system
        types: [ rust ]
        pass_filenames: false
        stages: [ pre-commit, pre-push ]
#      - id: lint
#        name: Run clippy
#        entry: cargo clippy --workspace --fix --allow-staged --allow-dirty -- -Dwarnings
#        language: system
#        types: [ rust ]
#        pass_filenames: false
#        # don't automatically commit changes made by clippy
#        stages: [ commit ]
