[config]
default_to_workspace = false
skip_core_tasks = true
init_task = "prep"
end_task = "stat"

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
SCCACHE_CACHE_SIZE = "20G"

[tasks.prep]
description = "Ensure all tools are installed"
script = [
    "cargo binstall sqlx-cli@^0.7 --no-confirm || true",
    "cargo binstall cargo-nextest@^0.9 --no-confirm || true",
    "cargo binstall cargo-watch@^7.8 --no-confirm || true",
    "sccache --show-stats || cargo binstall sccache@^0.7 || true",
    "sccache --start-server || true",
    "cd localchain && cargo sqlx database setup|| true",
    "cd notary && cargo sqlx database setup || true",
]

[tasks.docker]
description = "Build docker image"
script = [
    "docker buildx build -t ghcr.io/ulixee/ulixee-miner:dev . -f dev.Dockerfile --target ulx-node",
    "docker buildx build -t ghcr.io/ulixee/ulixee-notary:dev . -f dev.Dockerfile --target ulx-notary",
]

[tasks.sqlx]
description = "Run sqlx prepare"
command = "cargo"
args = ["sqlx", "prepare", "--workspace", "--", "--profile=test"]

[tasks.stat]
description = "Show sccache stats"
command = "sccache"
args = ["--show-stats"]

[tasks.build]
description = "Compiles the project"
command = "cargo"
args = ["build", "--features", "fast-runtime"]
env = { "RUSTC_WRAPPER" = "sccache" }

[tasks.test]
description = "Run tests with nextest,"
command = "cargo"
args = ["nextest", "run", "--features", "fast-runtime"]
dependencies = ["build"]
env = { "RUSTC_WRAPPER" = "sccache" }

[tasks.watch]
description = "Watch for changes and rebuild"
command = "cargo"
args = ["watch", "-x", "build", "--features", "fast-runtime"]
env = { "RUSTC_WRAPPER" = "sccache" }


[tasks.build-ci]
description = "Compiles the project for CI with --locked"
command = "cargo"
args = ["build", "--features", "fast-runtime", "--locked"]
env = { "RUSTC_WRAPPER" = "sccache" }

[tasks.test-ci]
description = "Tasks to run in CI for fast builds"
command = "cargo"
args = ["nextest", "run", "--features", "fast-runtime", "--profile", "ci"]
dependencies = ["build-ci"]
env = { "RUSTC_WRAPPER" = "sccache" }

