[toolchain]
channel = "1.87.0"
components = [
    "cargo",
    "clippy",
    "rust-analyzer",
    "rust-std",
    "rustc",
    "rustc-dev",
    "rustfmt",
]
targets = ["wasm32v1-none"]
profile = "minimal"
