[package]
name = "ulx-notary-audit"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true

[dependencies]

log = { version = "0.4.20", default-features = false }
anyhow = { version = "1.0", default-features = false }
codec = { package = "parity-scale-codec", version = "3.6", default-features = false, features = ["derive", "max-encoded-len"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.10", default-features = false, features = ["derive"] }
sp-core = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.8.0", features = ["serde"] }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.8.0" }
sp-std = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.8.0" }
snafu = { version = "0.7", default-features = false }
binary-merkle-tree = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.8.0" }

ulx-primitives = { path = "../../primitives", default-features = false }

[dev-dependencies]
frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.8.0" }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.8.0" }
chrono = "0.4"

[features]
default = ["std"]
std = [
    "anyhow/std",
    "codec/std",
    "snafu/std",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "binary-merkle-tree/std",
    "ulx-primitives/std"
]
fast-runtime = ["ulx-primitives/fast-runtime"]