[package]
name = "ulx-notary-audit"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", default-features = false }
codec = { package = "parity-scale-codec", version = "3.6", default-features = false, features = ["derive", "max-encoded-len"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sp-core = { version = "21.0.0",default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0", features = [ "serde"] }
sp-runtime = { version = "24.0.0", default-features = false,git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
sp-std = { version = "8.0.0" , default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
thiserror = { version ="1.0", default-features = false  }
binary-merkle-tree = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }

ulx-notary-primitives = { path = "../primitives", default-features = false }

[dev-dependencies]
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
sp-keyring = { version = "24.0.0", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
chrono = "0.4"
tokio = { version = "1.33", features = ["test-util", "macros"] }

[features]
default = ["std"]
std = [
    "anyhow/std",
    "codec/std",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "binary-merkle-tree/std",
    "ulx-notary-primitives/std"
]
