
//! Autogenerated weights for `pallet_treasury_positions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-10-07, STEPS: `10`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mac`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/Volumes/BuildCache/by-path/Users/blakebyrnes/.codex/worktrees/2a5e/mainchain/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_treasury_positions
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --steps=10
// --repeat=10
// --hostname-override=mac
// --output=runtime/argon/src/weights/
// --json-file=/private/tmp/upstream-argon-pallet_treasury_positions.json

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_treasury_positions`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_treasury_positions::WeightInfo for WeightInfo<T> {
	/// Storage: `TreasuryPositions::PositionsByAccount` (r:1 w:0)
	/// Proof: `TreasuryPositions::PositionsByAccount` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn bond_principal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3630`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 3630)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `TreasuryPositions::PositionsByAccount` (r:1 w:0)
	/// Proof: `TreasuryPositions::PositionsByAccount` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn account_quantities() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3630`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 3630)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `TreasuryPositions::NetworkTotals` (r:1 w:0)
	/// Proof: `TreasuryPositions::NetworkTotals` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
	fn network_totals() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1533`
		// Minimum execution time: 0_000 picoseconds.
		Weight::from_parts(1_000_000, 1533)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `TreasuryPositions::PositionsByAccount` (r:1 w:1)
	/// Proof: `TreasuryPositions::PositionsByAccount` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryPositions::NetworkTotals` (r:1 w:1)
	/// Proof: `TreasuryPositions::NetworkTotals` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
	fn account_quantity_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `67`
		//  Estimated: `3630`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 3630)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `TreasuryPositions::PositionsByAccount` (r:1 w:0)
	/// Proof: `TreasuryPositions::PositionsByAccount` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn upstream_position() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3630`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 3630)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `TreasuryPositions::PositionsByAccount` (r:1 w:1)
	/// Proof: `TreasuryPositions::PositionsByAccount` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn set_upstream_position() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3630`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 3630)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `TreasuryPositions::PositionsByAccount` (r:1 w:1)
	/// Proof: `TreasuryPositions::PositionsByAccount` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn bitcoin_position_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3630`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 3630)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `TreasuryPositions::PositionsByAccount` (r:1 w:1)
	/// Proof: `TreasuryPositions::PositionsByAccount` (`max_values`: None, `max_size`: Some(165), added: 2640, mode: `MaxEncodedLen`)
	fn bond_position_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3630`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(3_000_000, 3630)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	}
