
//! Autogenerated weights for `pallet_crosschain_transfer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-05-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_crosschain_transfer
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/argon/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_crosschain_transfer`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_crosschain_transfer::WeightInfo for WeightInfo<T> {
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_chain_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `84`
		//  Estimated: `3593`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `CrosschainTransfer::GatewayStateBySourceChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::GatewayStateBySourceChain` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:26 w:26)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::RecentArgonTransfersByAccount` (r:25 w:25)
	/// Proof: `CrosschainTransfer::RecentArgonTransfersByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Ticks::CurrentTick` (r:1 w:0)
	/// Proof: `Ticks::CurrentTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::InboundTransfersExpiringAt` (r:1 w:1)
	/// Proof: `CrosschainTransfer::InboundTransfersExpiringAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[1, 10]`.
	/// The range of component `e` is `[0, 15]`.
	fn prove_gateway_activity(b: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `136`
		//  Estimated: `3601 + b * (2603 +/- 0) + e * (2603 +/- 0)`
		// Minimum execution time: 458_000_000 picoseconds.
		Weight::from_parts(466_000_000, 3601)
			// Standard Error: 533_815
			.saturating_add(Weight::from_parts(15_800_067, 0).saturating_mul(b.into()))
			// Standard Error: 357_943
			.saturating_add(Weight::from_parts(27_379_870, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(e.into())))
				.saturating_add(Weight::from_parts(0, 2603).saturating_mul(b.into()))
				.saturating_add(Weight::from_parts(0, 2603).saturating_mul(e.into()))
		}
	/// Storage: `Ticks::CurrentTick` (r:1 w:0)
	/// Proof: `Ticks::CurrentTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::LastTransferExpiryCleanupTick` (r:1 w:1)
	/// Proof: `CrosschainTransfer::LastTransferExpiryCleanupTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::InboundTransfersExpiringAt` (r:1 w:1)
	/// Proof: `CrosschainTransfer::InboundTransfersExpiringAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CrosschainTransfer::RecentArgonTransfersByAccount` (r:999 w:999)
	/// Proof: `CrosschainTransfer::RecentArgonTransfersByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[1, 1000]`.
	fn on_initialize_cleanup(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `63 + e * (89 +/- 0)`
		//  Estimated: `3537 + e * (2527 +/- 0)`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3537)
			// Standard Error: 7_673
			.saturating_add(Weight::from_parts(3_822_009, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(e.into())))
				.saturating_add(Weight::from_parts(0, 2527).saturating_mul(e.into()))
		}
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(78), added: 2553, mode: `MaxEncodedLen`)
	fn provider_is_crosschain_activated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `53`
		//  Estimated: `3543`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 3543)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `CrosschainTransfer::RecentArgonTransfersByAccount` (r:1 w:0)
	/// Proof: `CrosschainTransfer::RecentArgonTransfersByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn provider_has_recent_argon_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `57`
		//  Estimated: `3517`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(3_000_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	}
