
//! Autogenerated weights for `pallet_inbound_transfer_log`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-03-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_inbound_transfer_log
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/argon/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_inbound_transfer_log`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_inbound_transfer_log::WeightInfo for WeightInfo<T> {
	/// Storage: `InboundTransferLog::InboundTransfersExpiringAt` (r:1 w:1)
	/// Proof: `InboundTransferLog::InboundTransfersExpiringAt` (`max_values`: None, `max_size`: Some(3214), added: 5689, mode: `MaxEncodedLen`)
	/// Storage: `InboundTransferLog::InboundEvmTransfers` (r:100 w:100)
	/// Proof: `InboundTransferLog::InboundEvmTransfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `InboundTransferLog::RecentArgonTransfersByAccount` (r:100 w:100)
	/// Proof: `InboundTransferLog::RecentArgonTransfersByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 1024]`.
	fn on_initialize_cleanup(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `23302`
		//  Estimated: `213350 + c * (84 +/- 6)`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(616_190_511, 213350)
			// Standard Error: 20_252
			.saturating_add(Weight::from_parts(251_014, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(158))
			.saturating_add(T::DbWeight::get().writes(158))
				.saturating_add(Weight::from_parts(0, 84).saturating_mul(c.into()))
		}
	/// Storage: `TokenGateway::LocalAssets` (r:1 w:0)
	/// Proof: `TokenGateway::LocalAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::Precisions` (r:1 w:0)
	/// Proof: `TokenGateway::Precisions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `InboundTransferLog::RecentArgonTransfersByAccount` (r:1 w:1)
	/// Proof: `InboundTransferLog::RecentArgonTransfersByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `InboundTransferLog::InboundTransfersExpiringAt` (r:1 w:1)
	/// Proof: `InboundTransferLog::InboundTransfersExpiringAt` (`max_values`: None, `max_size`: Some(3214), added: 5689, mode: `MaxEncodedLen`)
	/// Storage: `InboundTransferLog::InboundEvmTransfers` (r:0 w:1)
	/// Proof: `InboundTransferLog::InboundEvmTransfers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_token_gateway_request_recorded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `6679`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(17_000_000, 6679)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `TokenGateway::LocalAssets` (r:1 w:0)
	/// Proof: `TokenGateway::LocalAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::Precisions` (r:1 w:0)
	/// Proof: `TokenGateway::Precisions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_token_gateway_request_dropped() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41`
		//  Estimated: `3506`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3506)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	}
