
//! Autogenerated weights for `pallet_ethereum_verifier`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-05-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_ethereum_verifier
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/argon/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_ethereum_verifier`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_ethereum_verifier::WeightInfo for WeightInfo<T> {
	/// Storage: `EthereumVerifier::BeaconPreset` (r:1 w:0)
	/// Proof: `EthereumVerifier::BeaconPreset` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconStateIndex` (r:1 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconStateIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconStateMapping` (r:1 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconStateMapping` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::NextSyncCommittee` (r:0 w:1)
	/// Proof: `EthereumVerifier::NextSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92374), added: 92869, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ForkVersionSchedule` (r:0 w:1)
	/// Proof: `EthereumVerifier::ForkVersionSchedule` (`max_values`: Some(1), `max_size`: Some(84), added: 579, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::InitialCheckpointRoot` (r:0 w:1)
	/// Proof: `EthereumVerifier::InitialCheckpointRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ExecutionHeaderAnchors` (r:0 w:1)
	/// Proof: `EthereumVerifier::ExecutionHeaderAnchors` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ValidatorsRoot` (r:0 w:1)
	/// Proof: `EthereumVerifier::ValidatorsRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestFinalizedBlockRoot` (r:0 w:1)
	/// Proof: `EthereumVerifier::LatestFinalizedBlockRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::CurrentSyncCommittee` (r:0 w:1)
	/// Proof: `EthereumVerifier::CurrentSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92374), added: 92869, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestExecutionHeaderAnchorBlockHash` (r:0 w:1)
	/// Proof: `EthereumVerifier::LatestExecutionHeaderAnchorBlockHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedExecutionHeaderAnchor` (r:0 w:1)
	/// Proof: `EthereumVerifier::FinalizedExecutionHeaderAnchor` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconState` (r:0 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconState` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn force_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3501`
		// Minimum execution time: 66_789_000_000 picoseconds.
		Weight::from_parts(67_567_000_000, 3501)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(12))
		}
	/// Storage: `EthereumVerifier::OperatingMode` (r:1 w:0)
	/// Proof: `EthereumVerifier::OperatingMode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::BeaconPreset` (r:1 w:0)
	/// Proof: `EthereumVerifier::BeaconPreset` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestFinalizedBlockRoot` (r:1 w:0)
	/// Proof: `EthereumVerifier::LatestFinalizedBlockRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconState` (r:1 w:0)
	/// Proof: `EthereumVerifier::FinalizedBeaconState` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::NextSyncCommittee` (r:1 w:0)
	/// Proof: `EthereumVerifier::NextSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92374), added: 92869, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ForkVersionSchedule` (r:1 w:0)
	/// Proof: `EthereumVerifier::ForkVersionSchedule` (`max_values`: Some(1), `max_size`: Some(84), added: 579, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::CurrentSyncCommittee` (r:1 w:0)
	/// Proof: `EthereumVerifier::CurrentSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92374), added: 92869, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ValidatorsRoot` (r:1 w:0)
	/// Proof: `EthereumVerifier::ValidatorsRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestSyncCommitteeUpdatePeriod` (r:1 w:0)
	/// Proof: `EthereumVerifier::LatestSyncCommitteeUpdatePeriod` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn submit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `92502`
		//  Estimated: `93859`
		// Minimum execution time: 16_509_000_000 picoseconds.
		Weight::from_parts(16_951_000_000, 93859)
			.saturating_add(T::DbWeight::get().reads(9))
		}
	/// Storage: `EthereumVerifier::OperatingMode` (r:1 w:0)
	/// Proof: `EthereumVerifier::OperatingMode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::BeaconPreset` (r:1 w:0)
	/// Proof: `EthereumVerifier::BeaconPreset` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestFinalizedBlockRoot` (r:1 w:0)
	/// Proof: `EthereumVerifier::LatestFinalizedBlockRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconState` (r:1 w:0)
	/// Proof: `EthereumVerifier::FinalizedBeaconState` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::NextSyncCommittee` (r:1 w:1)
	/// Proof: `EthereumVerifier::NextSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92374), added: 92869, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ForkVersionSchedule` (r:1 w:0)
	/// Proof: `EthereumVerifier::ForkVersionSchedule` (`max_values`: Some(1), `max_size`: Some(84), added: 579, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::CurrentSyncCommittee` (r:1 w:0)
	/// Proof: `EthereumVerifier::CurrentSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92374), added: 92869, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ValidatorsRoot` (r:1 w:0)
	/// Proof: `EthereumVerifier::ValidatorsRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestSyncCommitteeUpdatePeriod` (r:1 w:1)
	/// Proof: `EthereumVerifier::LatestSyncCommitteeUpdatePeriod` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn submit_with_sync_committee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `92502`
		//  Estimated: `93859`
		// Minimum execution time: 83_939_000_000 picoseconds.
		Weight::from_parts(84_981_000_000, 93859)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `EthereumVerifier::OperatingMode` (r:1 w:0)
	/// Proof: `EthereumVerifier::OperatingMode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ExecutionHeaderAnchors` (r:1 w:0)
	/// Proof: `EthereumVerifier::ExecutionHeaderAnchors` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 10]`.
	/// The range of component `e` is `[0, 15]`.
	fn provider_verify_receipt_logs(b: u32, e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `71`
		//  Estimated: `3609`
		// Minimum execution time: 61_000_000 picoseconds.
		Weight::from_parts(3_593_338, 3609)
			// Standard Error: 34_437
			.saturating_add(Weight::from_parts(5_744_240, 0).saturating_mul(b.into()))
			// Standard Error: 21_117
			.saturating_add(Weight::from_parts(7_178_874, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(2))
		}
	/// Storage: `EthereumVerifier::LatestExecutionHeaderAnchorBlockHash` (r:1 w:0)
	/// Proof: `EthereumVerifier::LatestExecutionHeaderAnchorBlockHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ExecutionHeaderAnchors` (r:1 w:0)
	/// Proof: `EthereumVerifier::ExecutionHeaderAnchors` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn provider_latest_execution_block_number() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `143`
		//  Estimated: `3609`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 3609)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	/// Storage: `EthereumVerifier::LatestExecutionHeaderAnchorBlockHash` (r:1 w:0)
	/// Proof: `EthereumVerifier::LatestExecutionHeaderAnchorBlockHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ExecutionHeaderAnchors` (r:1 w:0)
	/// Proof: `EthereumVerifier::ExecutionHeaderAnchors` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn provider_latest_execution_block_timestamp() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `143`
		//  Estimated: `3609`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 3609)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	}
