
//! Autogenerated weights for `pallet_bitcoin_utxos`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-08-19, STEPS: `50`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_bitcoin_utxos
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=5
// --output=runtime/argon/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_bitcoin_utxos`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_bitcoin_utxos::WeightInfo for WeightInfo<T> {
	/// Storage: `BitcoinUtxos::InherentIncluded` (r:1 w:1)
	/// Proof: `BitcoinUtxos::InherentIncluded` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::SynchedBitcoinBlock` (r:1 w:1)
	/// Proof: `BitcoinUtxos::SynchedBitcoinBlock` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn sync_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45`
		//  Estimated: `1525`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 1525)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:0 w:1)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::TempParentHasSyncState` (r:0 w:1)
	/// Proof: `BitcoinUtxos::TempParentHasSyncState` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn on_initialize_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `23`
		//  Estimated: `1525`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(3_000_000, 1525)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `BitcoinUtxos::OracleOperatorAccount` (r:1 w:0)
	/// Proof: `BitcoinUtxos::OracleOperatorAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:1)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn set_confirmed_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1525`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 1525)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `BitcoinUtxos::OracleOperatorAccount` (r:0 w:1)
	/// Proof: `BitcoinUtxos::OracleOperatorAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `BitcoinUtxos::UtxoRefsByUtxoId` (r:20 w:20)
	/// Proof: `BitcoinUtxos::UtxoRefsByUtxoId` (`max_values`: None, `max_size`: Some(3618), added: 6093, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn utxo_spent(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (57 +/- 0)`
		//  Estimated: `990 + n * (6093 +/- 0)`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(818_683, 990)
			// Standard Error: 46_334
			.saturating_add(Weight::from_parts(6_833_132, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
				.saturating_add(Weight::from_parts(0, 6093).saturating_mul(n.into()))
		}
	/// Storage: `BitcoinLocks::MinimumSatoshis` (r:1 w:0)
	/// Proof: `BitcoinLocks::MinimumSatoshis` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::UtxoAddressByUtxoId` (r:20 w:0)
	/// Proof: `BitcoinUtxos::UtxoAddressByUtxoId` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::UtxoIdByScriptPubkey` (r:20 w:0)
	/// Proof: `BitcoinUtxos::UtxoIdByScriptPubkey` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::UtxoRefsByUtxoId` (r:20 w:20)
	/// Proof: `BitcoinUtxos::UtxoRefsByUtxoId` (`max_values`: None, `max_size`: Some(3618), added: 6093, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn lock_verified(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (127 +/- 0)`
		//  Estimated: `1493 + n * (6093 +/- 0)`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(444_040, 1493)
			// Standard Error: 58_110
			.saturating_add(Weight::from_parts(10_118_691, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
				.saturating_add(Weight::from_parts(0, 6093).saturating_mul(n.into()))
		}
	}
