
//! Autogenerated weights for `pallet_notebook`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-02-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_notebook
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/argon/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_notebook`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_notebook::WeightInfo for WeightInfo<T> {
	/// Storage: `Notebook::InherentIncluded` (r:1 w:1)
	/// Proof: `Notebook::InherentIncluded` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Digests::TempDigests` (r:1 w:0)
	/// Proof: `Digests::TempDigests` (`max_values`: Some(1), `max_size`: Some(32009), added: 32504, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::NotariesLockedForFailedAudit` (r:100 w:0)
	/// Proof: `Notebook::NotariesLockedForFailedAudit` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::LockedNotaryReadyForReprocess` (r:100 w:0)
	/// Proof: `Notebook::LockedNotaryReadyForReprocess` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::LastNotebookDetailsByNotary` (r:100 w:100)
	/// Proof: `Notebook::LastNotebookDetailsByNotary` (`max_values`: None, `max_size`: Some(1781), added: 4256, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::NotebookChangedAccountsRootByNotary` (r:0 w:100)
	/// Proof: `Notebook::NotebookChangedAccountsRootByNotary` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::BlockNotebooks` (r:0 w:1)
	/// Proof: `Notebook::BlockNotebooks` (`max_values`: Some(1), `max_size`: Some(31746), added: 32241, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn submit(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `33494 + n * (4256 +/- 0)`
		// Minimum execution time: 55_000_000 picoseconds.
		Weight::from_parts(44_359_381, 33494)
			// Standard Error: 278_224
			.saturating_add(Weight::from_parts(47_776_301, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
				.saturating_add(Weight::from_parts(0, 4256).saturating_mul(n.into()))
		}
	/// Storage: `Notebook::InherentIncluded` (r:1 w:1)
	/// Proof: `Notebook::InherentIncluded` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Digests::TempDigests` (r:1 w:0)
	/// Proof: `Digests::TempDigests` (`max_values`: Some(1), `max_size`: Some(32009), added: 32504, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::NotariesLockedForFailedAudit` (r:1 w:0)
	/// Proof: `Notebook::NotariesLockedForFailedAudit` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::LockedNotaryReadyForReprocess` (r:1 w:0)
	/// Proof: `Notebook::LockedNotaryReadyForReprocess` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::LastNotebookDetailsByNotary` (r:1 w:1)
	/// Proof: `Notebook::LastNotebookDetailsByNotary` (`max_values`: None, `max_size`: Some(1781), added: 4256, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::NotebookChangedAccountsRootByNotary` (r:0 w:1)
	/// Proof: `Notebook::NotebookChangedAccountsRootByNotary` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::AccountOriginLastChangedNotebookByNotary` (r:0 w:999)
	/// Proof: `Notebook::AccountOriginLastChangedNotebookByNotary` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::BlockNotebooks` (r:0 w:1)
	/// Proof: `Notebook::BlockNotebooks` (`max_values`: Some(1), `max_size`: Some(31746), added: 32241, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[1, 1000]`.
	fn submit_with_account_origins(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `33494`
		// Minimum execution time: 55_000_000 picoseconds.
		Weight::from_parts(2_453_068, 33494)
			// Standard Error: 18_690
			.saturating_add(Weight::from_parts(2_204_449, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
		}
	/// Storage: `Notebook::InherentIncluded` (r:1 w:1)
	/// Proof: `Notebook::InherentIncluded` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Digests::TempDigests` (r:1 w:0)
	/// Proof: `Digests::TempDigests` (`max_values`: Some(1), `max_size`: Some(32009), added: 32504, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::NotariesLockedForFailedAudit` (r:1 w:0)
	/// Proof: `Notebook::NotariesLockedForFailedAudit` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::LockedNotaryReadyForReprocess` (r:1 w:0)
	/// Proof: `Notebook::LockedNotaryReadyForReprocess` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::LastNotebookDetailsByNotary` (r:1 w:1)
	/// Proof: `Notebook::LastNotebookDetailsByNotary` (`max_values`: None, `max_size`: Some(1781), added: 4256, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::NotebookChangedAccountsRootByNotary` (r:0 w:1)
	/// Proof: `Notebook::NotebookChangedAccountsRootByNotary` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::BlockNotebooks` (r:0 w:1)
	/// Proof: `Notebook::BlockNotebooks` (`max_values`: Some(1), `max_size`: Some(31746), added: 32241, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 10000]`.
	fn submit_with_chain_transfers(t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `33494`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(71_168_026, 33494)
			// Standard Error: 519
			.saturating_add(Weight::from_parts(46_599, 0).saturating_mul(t.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
		}
	/// Storage: `Notebook::NotariesLockedForFailedAudit` (r:1 w:1)
	/// Proof: `Notebook::NotariesLockedForFailedAudit` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::LockedNotaryReadyForReprocess` (r:0 w:1)
	/// Proof: `Notebook::LockedNotaryReadyForReprocess` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn unlock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `38`
		//  Estimated: `3604`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3604)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `Digests::TempDigests` (r:1 w:0)
	/// Proof: `Digests::TempDigests` (`max_values`: Some(1), `max_size`: Some(32009), added: 32504, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn provider_vote_eligible_notebook_count(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `33494`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(3_494_916, 33494)
			// Standard Error: 846
			.saturating_add(Weight::from_parts(79_269, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Notebook::BlockNotebooks` (r:1 w:0)
	/// Proof: `Notebook::BlockNotebooks` (`max_values`: Some(1), `max_size`: Some(31746), added: 32241, mode: `MaxEncodedLen`)
	fn provider_notebooks_in_block() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1226`
		//  Estimated: `33231`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(25_000_000, 33231)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Notebook::LastNotebookDetailsByNotary` (r:101 w:0)
	/// Proof: `Notebook::LastNotebookDetailsByNotary` (`max_values`: None, `max_size`: Some(1781), added: 4256, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn provider_eligible_notebooks_for_vote(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `717 + n * (1632 +/- 0)`
		//  Estimated: `5246 + n * (4256 +/- 0)`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(2_650_730, 5246)
			// Standard Error: 18_301
			.saturating_add(Weight::from_parts(5_595_027, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
				.saturating_add(Weight::from_parts(0, 4256).saturating_mul(n.into()))
		}
	/// Storage: `Notebook::NotariesLockedForFailedAudit` (r:1 w:0)
	/// Proof: `Notebook::NotariesLockedForFailedAudit` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Notebook::LastNotebookDetailsByNotary` (r:1 w:0)
	/// Proof: `Notebook::LastNotebookDetailsByNotary` (`max_values`: None, `max_size`: Some(1781), added: 4256, mode: `MaxEncodedLen`)
	fn provider_get_eligible_tick_votes_root() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1666`
		//  Estimated: `5246`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 5246)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	/// Storage: `Notebook::NotariesLockedForFailedAudit` (r:1 w:0)
	/// Proof: `Notebook::NotariesLockedForFailedAudit` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	fn provider_is_notary_locked_at_tick() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `38`
		//  Estimated: `3604`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(3_000_000, 3604)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	}
