
//! Autogenerated weights for `pallet_ticks`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-04-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_ticks
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/argon/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_ticks`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_ticks::WeightInfo for WeightInfo<T> {
	/// Storage: `Ticks::CurrentTick` (r:1 w:1)
	/// Proof: `Ticks::CurrentTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Digests::TempDigests` (r:1 w:0)
	/// Proof: `Digests::TempDigests` (`max_values`: Some(1), `max_size`: Some(32009), added: 32504, mode: `MaxEncodedLen`)
	/// Storage: `Ticks::RecentBlocksAtTicks` (r:1025 w:1024)
	/// Proof: `Ticks::RecentBlocksAtTicks` (`max_values`: None, `max_size`: Some(1937), added: 4412, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Ticks::GenesisTick` (r:1 w:0)
	/// Proof: `Ticks::GenesisTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Ticks::PreviousTick` (r:0 w:1)
	/// Proof: `Ticks::PreviousTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 1024]`.
	fn on_initialize_with_cleanup(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2029 + c * (55 +/- 0)`
		//  Estimated: `33494 + c * (4412 +/- 0)`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_000_000, 33494)
			// Standard Error: 7_765
			.saturating_add(Weight::from_parts(3_716_722, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
				.saturating_add(Weight::from_parts(0, 4412).saturating_mul(c.into()))
		}
	/// Storage: `Ticks::PreviousTick` (r:1 w:0)
	/// Proof: `Ticks::PreviousTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn provider_previous_tick() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12`
		//  Estimated: `1493`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(1_000_000, 1493)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Ticks::CurrentTick` (r:1 w:0)
	/// Proof: `Ticks::CurrentTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn provider_current_tick() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12`
		//  Estimated: `1493`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 1493)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Ticks::GenesisTick` (r:1 w:0)
	/// Proof: `Ticks::GenesisTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Ticks::CurrentTick` (r:1 w:0)
	/// Proof: `Ticks::CurrentTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn provider_elapsed_ticks() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `43`
		//  Estimated: `1493`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 1493)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	/// Storage: `Ticks::GenesisTicker` (r:1 w:0)
	/// Proof: `Ticks::GenesisTicker` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn provider_ticker() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7`
		//  Estimated: `1501`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(2_000_000, 1501)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Ticks::RecentBlocksAtTicks` (r:1 w:0)
	/// Proof: `Ticks::RecentBlocksAtTicks` (`max_values`: None, `max_size`: Some(1937), added: 4412, mode: `MaxEncodedLen`)
	fn provider_blocks_at_tick() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1944`
		//  Estimated: `5402`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 5402)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	}
