
//! Autogenerated weights for `pallet_vaults`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-02-09, STEPS: `50`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_vaults
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=2
// --output=runtime/argon/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_vaults`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_vaults::WeightInfo for WeightInfo<T> {
	/// Storage: `BitcoinUtxos::BitcoinNetwork` (r:1 w:0)
	/// Proof: `BitcoinUtxos::BitcoinNetwork` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:1)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::NextVaultId` (r:1 w:1)
	/// Proof: `Vaults::NextVaultId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultXPubById` (r:0 w:1)
	/// Proof: `Vaults::VaultXPubById` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:0 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(9000), added: 11475, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `3640`
		// Minimum execution time: 183_000_000 picoseconds.
		Weight::from_parts(185_000_000, 3640)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(9000), added: 11475, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn modify_funding() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9079`
		//  Estimated: `12465`
		// Minimum execution time: 66_000_000 picoseconds.
		Weight::from_parts(73_000_000, 12465)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(9000), added: 11475, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::MiningConfig` (r:1 w:0)
	/// Proof: `MiningSlot::MiningConfig` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::FrameRewardTicksRemaining` (r:1 w:0)
	/// Proof: `MiningSlot::FrameRewardTicksRemaining` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::PendingTermsModificationsByTick` (r:1 w:1)
	/// Proof: `Vaults::PendingTermsModificationsByTick` (`max_values`: None, `max_size`: Some(418), added: 2893, mode: `MaxEncodedLen`)
	fn modify_terms() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `624`
		//  Estimated: `12465`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_000_000, 12465)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(9000), added: 11475, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9079`
		//  Estimated: `12465`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(64_000_000, 12465)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(9000), added: 11475, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultXPubById` (r:1 w:1)
	/// Proof: `Vaults::VaultXPubById` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::BitcoinNetwork` (r:1 w:0)
	/// Proof: `BitcoinUtxos::BitcoinNetwork` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn replace_bitcoin_xpub() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `265`
		//  Estimated: `12465`
		// Minimum execution time: 136_000_000 picoseconds.
		Weight::from_parts(137_000_000, 12465)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(9000), added: 11475, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::PendingCosignByVaultId` (r:1 w:0)
	/// Proof: `Vaults::PendingCosignByVaultId` (`max_values`: None, `max_size`: Some(814), added: 3289, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::OrphanedUtxoAccountsByVaultId` (r:1 w:0)
	/// Proof: `Vaults::OrphanedUtxoAccountsByVaultId` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::LastCollectFrameByVaultId` (r:0 w:1)
	/// Proof: `Vaults::LastCollectFrameByVaultId` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn collect() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `740`
		//  Estimated: `12465`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(78_000_000, 12465)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:101 w:100)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:100 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(9000), added: 11475, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:100)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:100 w:100)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 100]`.
	fn on_frame_start(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `137 + v * (592 +/- 0)`
		//  Estimated: `6118 + v * (11475 +/- 0)`
		// Minimum execution time: 287_000_000 picoseconds.
		Weight::from_parts(287_000_000, 6118)
			// Standard Error: 1_018_078
			.saturating_add(Weight::from_parts(250_012_987, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 11475).saturating_mul(v.into()))
	}
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultFundsReleasingByHeight` (r:366 w:100)
	/// Proof: `Vaults::VaultFundsReleasingByHeight` (`max_values`: None, `max_size`: Some(40018), added: 42493, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:100 w:100)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(9000), added: 11475, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:100 w:100)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:100)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `h` is `[1, 366]`.
	/// The range of component `v` is `[1, 100]`.
	fn on_initialize_with_vault_releases(h: u32, v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + v * (9106 +/- 0)`
		//  Estimated: `1525 + h * (42493 +/- 0) + v * (11475 +/- 0)`
		// Minimum execution time: 633_000_000 picoseconds.
		Weight::from_parts(633_000_000, 1525)
			// Standard Error: 558_249
			.saturating_add(Weight::from_parts(2_337_875, 0).saturating_mul(h.into()))
			// Standard Error: 2_045_242
			.saturating_add(Weight::from_parts(68_070_980, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(h.into())))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((4_u64).saturating_mul(v.into())))
			.saturating_add(Weight::from_parts(0, 42493).saturating_mul(h.into()))
			.saturating_add(Weight::from_parts(0, 11475).saturating_mul(v.into()))
	}
}
