
//! Autogenerated weights for `pallet_vaults`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-10-08, STEPS: `10`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mac`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// /Users/blakebyrnes/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/Volumes/BuildCache/by-path/Users/blakebyrnes/.codex/worktrees/2a5e/mainchain/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_vaults
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --steps=10
// --repeat=10
// --hostname-override=mac
// --output=/private/tmp/upstream-pr-prep/argon-vaults.rs
// --json-file=/private/tmp/upstream-pr-prep/argon-vaults.json

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_vaults`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_vaults::WeightInfo for WeightInfo<T> {
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	fn provider_get_vault_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4650`
		//  Estimated: `30138`
		// Minimum execution time: 61_000_000 picoseconds.
		Weight::from_parts(61_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn provider_get_participation_capacity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6892`
		//  Estimated: `30138`
		// Minimum execution time: 76_000_000 picoseconds.
		Weight::from_parts(77_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(3))
		}
	/// Storage: `BitcoinUtxos::BitcoinNetwork` (r:1 w:0)
	/// Proof: `BitcoinUtxos::BitcoinNetwork` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:1)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::NextVaultId` (r:1 w:1)
	/// Proof: `Vaults::NextVaultId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::TotalVaultSecuritization` (r:1 w:1)
	/// Proof: `Vaults::TotalVaultSecuritization` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultXPubById` (r:0 w:1)
	/// Proof: `Vaults::VaultXPubById` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultSecuritizationRanks` (r:0 w:1)
	/// Proof: `Vaults::VaultSecuritizationRanks` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:0 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `3676`
		// Minimum execution time: 175_000_000 picoseconds.
		Weight::from_parts(176_000_000, 3676)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(9))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultFundsReleasingByHeight` (r:1 w:1)
	/// Proof: `Vaults::VaultFundsReleasingByHeight` (`max_values`: None, `max_size`: Some(40018), added: 42493, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::TotalVaultSecuritization` (r:1 w:1)
	/// Proof: `Vaults::TotalVaultSecuritization` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultSecuritizationRanks` (r:0 w:2)
	/// Proof: `Vaults::VaultSecuritizationRanks` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn modify_funding() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13435`
		//  Estimated: `43483`
		// Minimum execution time: 161_000_000 picoseconds.
		Weight::from_parts(162_000_000, 43483)
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(8))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::MiningConfig` (r:1 w:0)
	/// Proof: `MiningSlot::MiningConfig` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::FrameRewardTicksRemaining` (r:1 w:0)
	/// Proof: `MiningSlot::FrameRewardTicksRemaining` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::PendingTermsModificationsByTick` (r:1 w:1)
	/// Proof: `Vaults::PendingTermsModificationsByTick` (`max_values`: None, `max_size`: Some(418), added: 2893, mode: `MaxEncodedLen`)
	fn modify_terms() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `694`
		//  Estimated: `30138`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultFundsReleasingByHeight` (r:1 w:1)
	/// Proof: `Vaults::VaultFundsReleasingByHeight` (`max_values`: None, `max_size`: Some(40018), added: 42493, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::TotalVaultSecuritization` (r:1 w:1)
	/// Proof: `Vaults::TotalVaultSecuritization` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultSecuritizationRanks` (r:0 w:1)
	/// Proof: `Vaults::VaultSecuritizationRanks` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13435`
		//  Estimated: `43483`
		// Minimum execution time: 160_000_000 picoseconds.
		Weight::from_parts(162_000_000, 43483)
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(7))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultXPubById` (r:1 w:1)
	/// Proof: `Vaults::VaultXPubById` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::BitcoinNetwork` (r:1 w:0)
	/// Proof: `BitcoinUtxos::BitcoinNetwork` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn replace_bitcoin_xpub() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `335`
		//  Estimated: `30138`
		// Minimum execution time: 128_000_000 picoseconds.
		Weight::from_parts(139_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	fn set_delegate_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `30138`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	fn set_reserved_securitization_space() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `291`
		//  Estimated: `30138`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::ArgonotSecuritizationByVaultId` (r:1 w:1)
	/// Proof: `Vaults::ArgonotSecuritizationByVaultId` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Holds` (r:1 w:1)
	/// Proof: `Ownership::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:1 w:1)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	fn set_argonot_securitization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `441`
		//  Estimated: `30138`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(50_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::PendingCosignByVaultId` (r:1 w:0)
	/// Proof: `Vaults::PendingCosignByVaultId` (`max_values`: None, `max_size`: Some(814), added: 3289, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::OrphanedUtxoAccountsByVaultId` (r:1 w:0)
	/// Proof: `Vaults::OrphanedUtxoAccountsByVaultId` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::LastCollectFrameByVaultId` (r:0 w:1)
	/// Proof: `Vaults::LastCollectFrameByVaultId` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn collect() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `839`
		//  Estimated: `30138`
		// Minimum execution time: 55_000_000 picoseconds.
		Weight::from_parts(55_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	fn provider_get_registration_vault_data() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `30138`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::FrameRewardTicksRemaining` (r:1 w:0)
	/// Proof: `MiningSlot::FrameRewardTicksRemaining` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn provider_get_committed_securitization() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `30138`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(5))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::ArgonotSecuritizationByVaultId` (r:1 w:0)
	/// Proof: `Vaults::ArgonotSecuritizationByVaultId` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn provider_get_held_argonots() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247`
		//  Estimated: `3525`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3525)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	/// Storage: `Vaults::VaultSecuritizationRanks` (r:100 w:0)
	/// Proof: `Vaults::VaultSecuritizationRanks` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:100 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::ArgonotSecuritizationByVaultId` (r:100 w:0)
	/// Proof: `Vaults::ArgonotSecuritizationByVaultId` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Holds` (r:100 w:0)
	/// Proof: `Ownership::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::TotalVaultSecuritization` (r:1 w:0)
	/// Proof: `Vaults::TotalVaultSecuritization` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 100]`.
	fn provider_get_top_vaults_by_securitization(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `177 + v * (97 +/- 0)`
		//  Estimated: `1501 + v * (29148 +/- 0)`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(8_414_967, 1501)
			// Standard Error: 48_657
			.saturating_add(Weight::from_parts(6_775_941, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(v.into())))
				.saturating_add(Weight::from_parts(0, 29148).saturating_mul(v.into()))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::ArgonotSecuritizationByVaultId` (r:1 w:1)
	/// Proof: `Vaults::ArgonotSecuritizationByVaultId` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn provider_commit_securitization_for_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `291`
		//  Estimated: `30138`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:1 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVaultCount` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVaultCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn provider_record_vault_frame_earnings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `545`
		//  Estimated: `30138`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(44_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	fn provider_set_bitcoin_lock_flexible() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `256`
		//  Estimated: `30138`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVaultCount` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVaultCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[1, 366]`.
	fn provider_reserve_securitization(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `550 + e * (18 +/- 0)`
		//  Estimated: `30138`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(54_652_405, 30138)
			// Standard Error: 2_818
			.saturating_add(Weight::from_parts(387_935, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(6))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVaultCount` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVaultCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[1, 366]`.
	fn provider_resecuritize_unfunded(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `560 + e * (18 +/- 0)`
		//  Estimated: `30138`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(52_895_656, 30138)
			// Standard Error: 3_315
			.saturating_add(Weight::from_parts(396_801, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(6))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVaultCount` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVaultCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultFundsReleasingByHeight` (r:366 w:366)
	/// Proof: `Vaults::VaultFundsReleasingByHeight` (`max_values`: None, `max_size`: Some(40018), added: 42493, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[1, 366]`.
	fn provider_resecuritize(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `566 + e * (21 +/- 0)`
		//  Estimated: `30138 + e * (42493 +/- 0)`
		// Minimum execution time: 54_000_000 picoseconds.
		Weight::from_parts(53_633_740, 30138)
			// Standard Error: 9_790
			.saturating_add(Weight::from_parts(2_561_439, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(e.into())))
				.saturating_add(Weight::from_parts(0, 42493).saturating_mul(e.into()))
		}
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVaultCount` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVaultCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultFundsReleasingByHeight` (r:366 w:366)
	/// Proof: `Vaults::VaultFundsReleasingByHeight` (`max_values`: None, `max_size`: Some(40018), added: 42493, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::TotalVaultSecuritization` (r:1 w:1)
	/// Proof: `Vaults::TotalVaultSecuritization` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultSecuritizationRanks` (r:0 w:2)
	/// Proof: `Vaults::VaultSecuritizationRanks` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[1, 366]`.
	fn provider_burn(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8717 + e * (15 +/- 0)`
		//  Estimated: `30138 + e * (42493 +/- 0)`
		// Minimum execution time: 88_000_000 picoseconds.
		Weight::from_parts(78_743_834, 30138)
			// Standard Error: 13_986
			.saturating_add(Weight::from_parts(2_562_749, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(e.into())))
				.saturating_add(Weight::from_parts(0, 42493).saturating_mul(e.into()))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::ArgonotSecuritizationByVaultId` (r:1 w:1)
	/// Proof: `Vaults::ArgonotSecuritizationByVaultId` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn provider_encumber_argonots() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `247`
		//  Estimated: `3525`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3525)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::ArgonotSecuritizationByVaultId` (r:1 w:1)
	/// Proof: `Vaults::ArgonotSecuritizationByVaultId` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	fn provider_release_encumbered_argonots() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `250`
		//  Estimated: `3525`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3525)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::ArgonotSecuritizationByVaultId` (r:1 w:1)
	/// Proof: `Vaults::ArgonotSecuritizationByVaultId` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:1 w:1)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Holds` (r:1 w:1)
	/// Proof: `Ownership::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	fn provider_burn_encumbered_argonots() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `537`
		//  Estimated: `30138`
		// Minimum execution time: 33_000_000 picoseconds.
		Weight::from_parts(34_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
		}
	/// Storage: `Vaults::VaultIdByOperator` (r:1 w:0)
	/// Proof: `Vaults::VaultIdByOperator` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:1 w:1)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	fn provider_account_became_operational() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `30138`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 30138)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:101 w:100)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:100 w:0)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:100)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:100 w:100)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVaultCount` (r:1 w:1)
	/// Proof: `Vaults::RevenuePerFrameByVaultCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 100]`.
	fn on_frame_start(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `226 + v * (596 +/- 0)`
		//  Estimated: `6118 + v * (29148 +/- 0)`
		// Minimum execution time: 280_000_000 picoseconds.
		Weight::from_parts(63_202_662, 6118)
			// Standard Error: 642_324
			.saturating_add(Weight::from_parts(278_745_821, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(v.into())))
				.saturating_add(Weight::from_parts(0, 29148).saturating_mul(v.into()))
		}
	/// Storage: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::ConfirmedBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinUtxos::PreviousBitcoinBlockTip` (r:1 w:0)
	/// Proof: `BitcoinUtxos::PreviousBitcoinBlockTip` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultFundsReleasingByHeight` (r:366 w:100)
	/// Proof: `Vaults::VaultFundsReleasingByHeight` (`max_values`: None, `max_size`: Some(40018), added: 42493, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultsById` (r:100 w:100)
	/// Proof: `Vaults::VaultsById` (`max_values`: None, `max_size`: Some(26673), added: 29148, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:100)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:100 w:100)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::ArgonotSecuritizationByVaultId` (r:100 w:0)
	/// Proof: `Vaults::ArgonotSecuritizationByVaultId` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Holds` (r:100 w:0)
	/// Proof: `Ownership::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::TotalVaultSecuritization` (r:1 w:1)
	/// Proof: `Vaults::TotalVaultSecuritization` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:100 w:100)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::VaultSecuritizationRanks` (r:0 w:200)
	/// Proof: `Vaults::VaultSecuritizationRanks` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// The range of component `h` is `[1, 366]`.
	/// The range of component `v` is `[1, 100]`.
	fn on_initialize_with_vault_releases(h: u32, v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7889 + h * (1 +/- 0) + v * (5116 +/- 0)`
		//  Estimated: `14743 + h * (42493 +/- 0) + v * (29148 +/- 0)`
		// Minimum execution time: 646_000_000 picoseconds.
		Weight::from_parts(665_000_000, 14743)
			// Standard Error: 1_382_569
			.saturating_add(Weight::from_parts(244_818_724, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(h.into())))
			.saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(v.into())))
			.saturating_add(T::DbWeight::get().writes(8))
			.saturating_add(T::DbWeight::get().writes((7_u64).saturating_mul(v.into())))
				.saturating_add(Weight::from_parts(0, 42493).saturating_mul(h.into()))
				.saturating_add(Weight::from_parts(0, 29148).saturating_mul(v.into()))
		}
	}
