
//! Autogenerated weights for `pallet_mining_slot`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-02-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-runtime/argon_runtime.compact.wasm
// --pallet=pallet_mining_slot
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/argon/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_mining_slot`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_mining_slot::WeightInfo for WeightInfo<T> {
	/// Storage: `MiningSlot::IsNextSlotBiddingOpen` (r:1 w:0)
	/// Proof: `MiningSlot::IsNextSlotBiddingOpen` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::BidsForNextSlotCohort` (r:1 w:1)
	/// Proof: `MiningSlot::BidsForNextSlotCohort` (`max_values`: Some(1), `max_size`: Some(25490), added: 25985, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::AccountIndexLookup` (r:2 w:0)
	/// Proof: `MiningSlot::AccountIndexLookup` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::ArgonotsPerMiningSeat` (r:1 w:0)
	/// Proof: `MiningSlot::ArgonotsPerMiningSeat` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Holds` (r:2 w:2)
	/// Proof: `Ownership::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:2 w:2)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextCohortSize` (r:1 w:0)
	/// Proof: `MiningSlot::NextCohortSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::HistoricalBidsPerSlot` (r:1 w:1)
	/// Proof: `MiningSlot::HistoricalBidsPerSlot` (`max_values`: Some(1), `max_size`: Some(521), added: 1016, mode: `MaxEncodedLen`)
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `18494`
		//  Estimated: `26975`
		// Minimum execution time: 243_000_000 picoseconds.
		Weight::from_parts(259_000_000, 26975)
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(8))
		}
	/// Storage: `MiningSlot::MiningConfig` (r:1 w:1)
	/// Proof: `MiningSlot::MiningConfig` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	fn configure_mining_slot_delay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `94`
		//  Estimated: `1509`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 1509)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `BlockSeal::IsBlockFromVoteSeal` (r:1 w:0)
	/// Proof: `BlockSeal::IsBlockFromVoteSeal` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NewlyStartedFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NewlyStartedFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::HasAddedGrandpaRotation` (r:1 w:1)
	/// Proof: `MiningSlot::HasAddedGrandpaRotation` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Grandpa::Authorities` (r:1 w:0)
	/// Proof: `Grandpa::Authorities` (`max_values`: Some(1), `max_size`: Some(40002), added: 40497, mode: `MaxEncodedLen`)
	/// Storage: `Grandpa::PendingChange` (r:1 w:1)
	/// Proof: `Grandpa::PendingChange` (`max_values`: Some(1), `max_size`: Some(40015), added: 40510, mode: `MaxEncodedLen`)
	/// Storage: `Grandpa::CurrentSetId` (r:1 w:1)
	/// Proof: `Grandpa::CurrentSetId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::TempFrameInfoDigest` (r:1 w:0)
	/// Proof: `MiningSlot::TempFrameInfoDigest` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::FrameRewardTicksRemaining` (r:1 w:0)
	/// Proof: `MiningSlot::FrameRewardTicksRemaining` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_finalize_grandpa_rotation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `185`
		//  Estimated: `41500`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(23_000_000, 41500)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `MiningSlot::AccountIndexLookup` (r:1 w:0)
	/// Proof: `MiningSlot::AccountIndexLookup` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::MinerNonceScoringByCohort` (r:1 w:1)
	/// Proof: `MiningSlot::MinerNonceScoringByCohort` (`max_values`: Some(1), `max_size`: Some(59141), added: 59636, mode: `MaxEncodedLen`)
	fn on_finalize_record_block_author() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `139`
		//  Estimated: `60626`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 60626)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `MiningSlot::HistoricalBidsPerSlot` (r:1 w:1)
	/// Proof: `MiningSlot::HistoricalBidsPerSlot` (`max_values`: Some(1), `max_size`: Some(521), added: 1016, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::MiningConfig` (r:1 w:0)
	/// Proof: `MiningSlot::MiningConfig` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::BidsForNextSlotCohort` (r:1 w:1)
	/// Proof: `MiningSlot::BidsForNextSlotCohort` (`max_values`: Some(1), `max_size`: Some(25490), added: 25985, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::ActiveMinersCount` (r:1 w:1)
	/// Proof: `MiningSlot::ActiveMinersCount` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::MinerNonceScoringByCohort` (r:1 w:1)
	/// Proof: `MiningSlot::MinerNonceScoringByCohort` (`max_values`: Some(1), `max_size`: Some(59141), added: 59636, mode: `MaxEncodedLen`)
	/// Storage: `System::ParentHash` (r:1 w:0)
	/// Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::MinersByCohort` (r:1 w:2)
	/// Proof: `MiningSlot::MinersByCohort` (`max_values`: None, `max_size`: Some(25514), added: 27989, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:144 w:144)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Holds` (r:144 w:144)
	/// Proof: `Ownership::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:144 w:144)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::AveragePricePerSeat` (r:1 w:1)
	/// Proof: `MiningSlot::AveragePricePerSeat` (`max_values`: Some(1), `max_size`: Some(161), added: 656, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::ScheduledCohortSizeChangeByFrame` (r:1 w:1)
	/// Proof: `MiningSlot::ScheduledCohortSizeChangeByFrame` (`max_values`: Some(1), `max_size`: Some(133), added: 628, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::FrameStartBlockNumbers` (r:1 w:1)
	/// Proof: `MiningSlot::FrameStartBlockNumbers` (`max_values`: Some(1), `max_size`: Some(41), added: 536, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::FrameStartTicks` (r:1 w:1)
	/// Proof: `MiningSlot::FrameStartTicks` (`max_values`: Some(1), `max_size`: Some(161), added: 656, mode: `MaxEncodedLen`)
	/// Storage: `Grandpa::Authorities` (r:1 w:0)
	/// Proof: `Grandpa::Authorities` (`max_values`: Some(1), `max_size`: Some(40002), added: 40497, mode: `MaxEncodedLen`)
	/// Storage: `Grandpa::PendingChange` (r:1 w:1)
	/// Proof: `Grandpa::PendingChange` (`max_values`: Some(1), `max_size`: Some(40015), added: 40510, mode: `MaxEncodedLen`)
	/// Storage: `Grandpa::CurrentSetId` (r:1 w:1)
	/// Proof: `Grandpa::CurrentSetId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `BlockRewards::BlockRewardsByCohort` (r:1 w:1)
	/// Proof: `BlockRewards::BlockRewardsByCohort` (`max_values`: Some(1), `max_size`: Some(265), added: 760, mode: `MaxEncodedLen`)
	/// Storage: `PriceIndex::Current` (r:1 w:0)
	/// Proof: `PriceIndex::Current` (`max_values`: Some(1), `max_size`: Some(88), added: 583, mode: `MaxEncodedLen`)
	/// Storage: `BlockRewards::ArgonsPerBlock` (r:1 w:1)
	/// Proof: `BlockRewards::ArgonsPerBlock` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Vaults::RevenuePerFrameByVault` (r:1 w:0)
	/// Proof: `Vaults::RevenuePerFrameByVault` (`max_values`: None, `max_size`: Some(2653), added: 5128, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::ReleasedMinersByAccountId` (r:0 w:1)
	/// Proof: `MiningSlot::ReleasedMinersByAccountId` (`max_values`: Some(1), `max_size`: Some(30098), added: 30593, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::FrameRewardTicksRemaining` (r:0 w:1)
	/// Proof: `MiningSlot::FrameRewardTicksRemaining` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::AccountIndexLookup` (r:0 w:288)
	/// Proof: `MiningSlot::AccountIndexLookup` (`max_values`: None, `max_size`: Some(60), added: 2535, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::IsNextSlotBiddingOpen` (r:0 w:1)
	/// Proof: `MiningSlot::IsNextSlotBiddingOpen` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:0 w:1)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[1, 256]`.
	fn start_new_frame(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `14565 + m * (396 +/- 0)`
		//  Estimated: `73319 + m * (1568 +/- 29)`
		// Minimum execution time: 81_000_000 picoseconds.
		Weight::from_parts(1_074_240_887, 73319)
			// Standard Error: 440_102
			.saturating_add(Weight::from_parts(24_113_615, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(100))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(154))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(m.into())))
				.saturating_add(Weight::from_parts(0, 1568).saturating_mul(m.into()))
		}
	/// Storage: `MiningSlot::AveragePricePerSeat` (r:1 w:0)
	/// Proof: `MiningSlot::AveragePricePerSeat` (`max_values`: Some(1), `max_size`: Some(161), added: 656, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::ScheduledCohortSizeChangeByFrame` (r:1 w:1)
	/// Proof: `MiningSlot::ScheduledCohortSizeChangeByFrame` (`max_values`: Some(1), `max_size`: Some(133), added: 628, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextCohortSize` (r:1 w:0)
	/// Proof: `MiningSlot::NextCohortSize` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn on_finalize_frame_adjustments() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `121`
		//  Estimated: `1646`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 1646)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `MiningSlot::IsNextSlotBiddingOpen` (r:1 w:1)
	/// Proof: `MiningSlot::IsNextSlotBiddingOpen` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::MiningConfig` (r:1 w:0)
	/// Proof: `MiningSlot::MiningConfig` (`max_values`: Some(1), `max_size`: Some(24), added: 519, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::FrameRewardTicksRemaining` (r:1 w:0)
	/// Proof: `MiningSlot::FrameRewardTicksRemaining` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn block_seal_read_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85`
		//  Estimated: `1509`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 1509)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	}
