name: Clear space
description: |
  Empty out extra space on the github runner

runs:
  using: "composite"
  steps:
    - name: Clear space
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        df -h
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /opt/hostedtoolcache/Go
        sudo rm -rf /opt/hostedtoolcache/Java
        sudo rm -rf /opt/hostedtoolcache/R
        sudo rm -rf /opt/hostedtoolcache/Node
        sudo rm -rf /opt/hostedtoolcache/PowerShell
        sudo rm -rf /opt/hostedtoolcache/Python
        sudo rm -rf /opt/hostedtoolcache/Php
        sudo rm -rf /opt/hostedtoolcache/Perl
        sudo rm -rf /opt/hostedtoolcache/Ruby
        sudo rm -rf /opt/hostedtoolcache/Swift
        sudo rm -rf /opt/hostedtoolcache/Scala

        docker system prune --all --force
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android/sdk
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/share/miniconda
        # Additional heavy caches
        sudo rm -rf /opt/az                 # Azure CLI tools (~500MB+)
        sudo rm -rf /opt/google             # Google Cloud SDK (~500MB+)
        sudo rm -rf /opt/microsoft          # Microsoft tools
        sudo rm -rf /opt/ghc                # Haskell GHC (~3GB)

        # Node/npm cache (safe if you're not using node/yarn)
        rm -rf ~/.npm ~/.cache/yarn ~/.cargo/registry
        df -h
    - name: Clear space
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        df -h
        sudo rm -rf /Users/runner/Library/Android/sdk
        sudo rm -rf /Users/runner/hostedtoolcache/CodeQL
        sudo rm -rf /Users/runner/Library/Developer/CoreSimulator
        sudo rm -rf /Users/runner/Library/Developer/Xcode/DerivedData
        sudo rm -rf /Users/runner/Library/Developer/Xcode/iOS DeviceSupport
        sudo rm -rf /Users/runner/Library/Developer/Xcode/watchOS DeviceSupport
        df -h
