name: Clear space
description: |
  Empty out extra space on the github runner

runs:
  using: "composite"
  steps:
    - name: Clear space
      shell: bash
      run: |
        df -h
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        docker system prune --all --force
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android/sdk
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/share/miniconda
        df -h
