name: Build Docker image
description: |
  Build a docker image with caching layers

inputs:
  image:
    description: 'The name of the image to build and push'
    required: true
  dockerfile:
    description: 'The path to the Dockerfile to build'
    required: false
    default: Containerfile
  bin:
    description: 'The bin name file to copy'
    required: true
  github-token:
    description: 'The github token'
    required: true
  flavor:
    description: 'The flavor of the image'
    required: false
    default: latest=false
  tags:
    description: 'The tags to apply to the image'
    required: false
    default: |
      type=raw,dev
      type=sha

runs:
  using: "composite"
  steps:
    - name: Set up tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        labels: |
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.vendor=argon
        flavor: ${{ inputs.flavor }}
        tags: ${{ inputs.tags }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: Build and push image to container registry
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        file: ${{ inputs.dockerfile }}
        bin: ${{ inputs.bin }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.image }}:buildcache
        cache-to: type=registry,ref=${{ inputs.image }}:buildcache,mode=max
