[package]
name = "ulx-testing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
publish = false

[dependencies]
ulixee-client = { path = "../client" }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.5.0" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
subxt = { version = "0.34", features = ["substrate-compat"] }
anyhow = "1.0"