name: Bug report
description: Report a problem or unexpected behavior
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the project! Please fill out the information below.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: What node version, OS, or platform are you using?
      placeholder: ex. Ubuntu 22.04, Rust 1.76, Argon 1.1.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the bug? Include steps to reproduce, expected behavior, and what actually happened.
      placeholder: Describe the bug here
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error output
      description: Paste any relevant log snippets or stack traces.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context about the issue, links, or references?
