blank_issues_enabled: false
contact_links:
  - name: Support & Troubleshooting with the Substrate Stack Exchange Community
    url: https://substrate.stackexchange.com
    about: Use for general Substrate-related questions and issues outside this repo.
  - name: Community Chat
    url: https://discord.gg/xDwwDgCYr9
    about: For real-time help or discussion about Argon
