name: Feature request
description: Suggest an idea or enhancement
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: input
    id: motivation
    attributes:
      label: What problem are you trying to solve?
      placeholder: I need to automate X / expose Y to clients / reduce time doing Z...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Describe the solution you'd like
      placeholder: I think we should...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Did you try other approaches or workarounds?
