
//! Autogenerated weights for `pallet_operational_accounts`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-08-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_operational_accounts
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_operational_accounts`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_operational_accounts::WeightInfo for WeightInfo<T> {
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:2)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:3 w:2)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::IsOperationalAccountInviteOnly` (r:1 w:0)
	/// Proof: `OperationalAccounts::IsOperationalAccountInviteOnly` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::AccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::AccessCodeReadyAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `8655`
		// Minimum execution time: 139_000_000 picoseconds.
		Weight::from_parts(405_000_000, 8655)
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn set_name() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `6620`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(26_000_000, 6620)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	fn on_vault_created() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `3805`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3805)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::AccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::AccessCodeReadyAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_vault_bitcoin_lock_funded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `6620`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(30_000_000, 6620)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::AccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::AccessCodeReadyAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_mining_seat_won() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `6620`
		// Minimum execution time: 30_000_000 picoseconds.
		Weight::from_parts(31_000_000, 6620)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `OperationalAccounts::AccessCodeReadyAccounts` (r:1000 w:999)
	/// Proof: `OperationalAccounts::AccessCodeReadyAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:999 w:999)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 1000]`.
	fn on_frame_start(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178 + r * (328 +/- 0)`
		//  Estimated: `3513 + r * (2815 +/- 0)`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3513)
			// Standard Error: 25_657
			.saturating_add(Weight::from_parts(10_996_301, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(r.into())))
				.saturating_add(Weight::from_parts(0, 2815).saturating_mul(r.into()))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn on_account_bitcoin_amount_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `6620`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 6620)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn on_account_vault_bond_total_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `6620`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 6620)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn on_account_uniswap_argon_transfers_in_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `6620`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 6620)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:3 w:2)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::Rewards` (r:1 w:0)
	/// Proof: `OperationalAccounts::Rewards` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::AccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::AccessCodeReadyAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::CounterForAccessCodeReadyAccounts` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn activate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `691`
		//  Estimated: `9435`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(25_000_000, 9435)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
		}
	/// Storage: `OperationalAccounts::Rewards` (r:0 w:1)
	/// Proof: `OperationalAccounts::Rewards` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_reward_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `6620`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(15_000_000, 6620)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(340), added: 2815, mode: `MaxEncodedLen`)
	fn force_set_progress() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `274`
		//  Estimated: `3805`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3805)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	}
