
//! Autogenerated weights for `pallet_treasury`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-10-07, STEPS: `10`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mac`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/Volumes/BuildCache/by-path/Users/blakebyrnes/.codex/worktrees/2a5e/mainchain/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_treasury
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --steps=10
// --repeat=10
// --hostname-override=mac
// --output=runtime/canary/src/weights/
// --json-file=/private/tmp/upstream-canary-pallet_treasury.json

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_treasury`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_treasury::WeightInfo for WeightInfo<T> {
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:0)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn upstream_participation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `3502`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3502)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Treasury::TotalArgonBondLots` (r:1 w:1)
	/// Proof: `Treasury::TotalArgonBondLots` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::LastBonusApprovalNonceByVaultAndAccount` (r:1 w:1)
	/// Proof: `Treasury::LastBonusApprovalNonceByVaultAndAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::NextBondLotId` (r:1 w:1)
	/// Proof: `Treasury::NextBondLotId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:0 w:1)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:0 w:1)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:0 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	fn buy_bonds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `14743`
		// Minimum execution time: 77_000_000 picoseconds.
		Weight::from_parts(78_000_000, 14743)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(8))
		}
	/// Storage: `Treasury::ArgonotBondLots` (r:1 w:1)
	/// Proof: `Treasury::ArgonotBondLots` (`max_values`: Some(1), `max_size`: Some(12002), added: 12497, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::NextBondLotId` (r:1 w:1)
	/// Proof: `Treasury::NextBondLotId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Holds` (r:1 w:1)
	/// Proof: `Ownership::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:1 w:1)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleasesByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingBondReleasesByFrame` (`max_values`: None, `max_size`: Some(8018), added: 10493, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1 w:2)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:0 w:1)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn buy_argonot_bonds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8187`
		//  Estimated: `13487`
		// Minimum execution time: 187_000_000 picoseconds.
		Weight::from_parts(207_000_000, 13487)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(8))
		}
	/// Storage: `Treasury::BondLotById` (r:1 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::ArgonotBondLots` (r:1 w:1)
	/// Proof: `Treasury::ArgonotBondLots` (`max_values`: Some(1), `max_size`: Some(12002), added: 12497, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleasesByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingBondReleasesByFrame` (`max_values`: None, `max_size`: Some(8018), added: 10493, mode: `MaxEncodedLen`)
	fn liquidate_bond_lot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5201`
		//  Estimated: `13487`
		// Minimum execution time: 92_000_000 picoseconds.
		Weight::from_parts(97_000_000, 13487)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `Treasury::BondLotById` (r:1 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	fn set_bond_lot_flexible() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `243`
		//  Estimated: `14743`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 14743)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn set_reserved_bond_space() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `77`
		//  Estimated: `3502`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3502)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::TargetBitcoinPercent` (r:0 w:1)
	/// Proof: `Treasury::TargetBitcoinPercent` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn configure_reward_economics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::BondLotById` (r:1 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn backfill_bond_lot_earnings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `213`
		//  Estimated: `3602`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(12_000_000, 3602)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `6196`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `Treasury::BondLotIdsByAccount` (r:1 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn provider_has_vault_bond_participation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `939`
		//  Estimated: `3521`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_000_000, 3521)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Treasury::BondLotIdsByAccount` (r:1 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn provider_active_vault_bond_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `939`
		//  Estimated: `3521`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 3521)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	fn provider_active_account_vault_bond_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 0_000 picoseconds.
		Weight::from_parts(0, 0)
		}
	/// Storage: `Treasury::EncumberedBondMicrogonsByAccount` (r:1 w:1)
	/// Proof: `Treasury::EncumberedBondMicrogonsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:2 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1 w:0)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	fn provider_encumber_bond_microgons() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `305`
		//  Estimated: `6052`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 6052)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::EncumberedBondMicrogonsByAccount` (r:1 w:1)
	/// Proof: `Treasury::EncumberedBondMicrogonsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:2 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1 w:0)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	fn provider_release_encumbered_bond_microgons() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `6052`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 6052)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::EncumberedBondMicrogonsByAccount` (r:1 w:1)
	/// Proof: `Treasury::EncumberedBondMicrogonsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:15000 w:14999)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:14999 w:14999)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TotalArgonBondLots` (r:1 w:1)
	/// Proof: `Treasury::TotalArgonBondLots` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:0 w:14999)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 14999]`.
	fn provider_burn_encumbered_bond_microgons(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11095 + n * (87 +/- 0)`
		//  Estimated: `14743 + n * (2612 +/- 0)`
		// Minimum execution time: 107_000_000 picoseconds.
		Weight::from_parts(109_000_000, 14743)
			// Standard Error: 116_740
			.saturating_add(Weight::from_parts(63_098_923, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(5))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
				.saturating_add(Weight::from_parts(0, 2612).saturating_mul(n.into()))
		}
	/// Storage: `Treasury::PendingBondReleaseRetryCursor` (r:1 w:0)
	/// Proof: `Treasury::PendingBondReleaseRetryCursor` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleasesByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingBondReleasesByFrame` (`max_values`: None, `max_size`: Some(8018), added: 10493, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1000 w:1000)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1000 w:1000)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1000 w:1000)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TotalArgonBondLots` (r:1 w:1)
	/// Proof: `Treasury::TotalArgonBondLots` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:0 w:1000)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:0 w:1000)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn release_pending_bond_lots() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299816`
		//  Estimated: `2686990`
		// Minimum execution time: 47_673_000_000 picoseconds.
		Weight::from_parts(48_646_000_000, 2686990)
			.saturating_add(T::DbWeight::get().reads(3003))
			.saturating_add(T::DbWeight::get().writes(5002))
		}
	/// Storage: `Treasury::CurrentFrameArgonotBondParticipants` (r:1 w:1)
	/// Proof: `Treasury::CurrentFrameArgonotBondParticipants` (`max_values`: Some(1), `max_size`: Some(12014), added: 12509, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:1)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:11202 w:11202)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:13600 w:13600)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:12601 w:0)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:100 w:0)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn distribute_bid_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1377789`
		//  Estimated: `35524190`
		// Minimum execution time: 639_703_000_000 picoseconds.
		Weight::from_parts(650_012_000_000, 35524190)
			.saturating_add(T::DbWeight::get().reads(37505))
			.saturating_add(T::DbWeight::get().writes(24804))
		}
	/// Storage: `Treasury::BondLotsByVault` (r:203 w:0)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Mint::MintedBitcoinMicrogons` (r:1 w:0)
	/// Proof: `Mint::MintedBitcoinMicrogons` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TargetBitcoinPercent` (r:1 w:0)
	/// Proof: `Treasury::TargetBitcoinPercent` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:0 w:1)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	fn lock_in_vault_capital() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5053`
		//  Estimated: `510926`
		// Minimum execution time: 16_847_000_000 picoseconds.
		Weight::from_parts(17_015_000_000, 510926)
			.saturating_add(T::DbWeight::get().reads(205))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::CurrentFrameArgonotBondParticipants` (r:1 w:1)
	/// Proof: `Treasury::CurrentFrameArgonotBondParticipants` (`max_values`: Some(1), `max_size`: Some(12014), added: 12509, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:1)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(13258), added: 13753, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:16002 w:16002)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:16000 w:16000)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:15001 w:1000)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleaseRetryCursor` (r:1 w:0)
	/// Proof: `Treasury::PendingBondReleaseRetryCursor` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleasesByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingBondReleasesByFrame` (`max_values`: None, `max_size`: Some(8018), added: 10493, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1000 w:1000)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TotalArgonBondLots` (r:1 w:1)
	/// Proof: `Treasury::TotalArgonBondLots` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::ArgonotBondLots` (r:1 w:0)
	/// Proof: `Treasury::ArgonotBondLots` (`max_values`: Some(1), `max_size`: Some(12002), added: 12497, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:203 w:0)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Mint::MintedBitcoinMicrogons` (r:1 w:0)
	/// Proof: `Mint::MintedBitcoinMicrogons` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TargetBitcoinPercent` (r:1 w:0)
	/// Proof: `Treasury::TargetBitcoinPercent` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:0 w:1000)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[0, 14000]`.
	/// The range of component `s` is `[0, 1000]`.
	/// The range of component `r` is `[0, 1000]`.
	fn on_frame_transition(b: u32, s: u32, r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `18819 + b * (91 +/- 0) + r * (330 +/- 0) + s * (209 +/- 0)`
		//  Estimated: `510926 + b * (2612 +/- 0) + r * (2686 +/- 0) + s * (2612 +/- 0)`
		// Minimum execution time: 131_802_000_000 picoseconds.
		Weight::from_parts(135_507_000_000, 510926)
			// Standard Error: 270_997
			.saturating_add(Weight::from_parts(45_315_737, 0).saturating_mul(b.into()))
			// Standard Error: 3_793_511
			.saturating_add(Weight::from_parts(5_061_997, 0).saturating_mul(s.into()))
			// Standard Error: 3_793_511
			.saturating_add(Weight::from_parts(21_592_617, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(214))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes((5_u64).saturating_mul(r.into())))
				.saturating_add(Weight::from_parts(0, 2612).saturating_mul(b.into()))
				.saturating_add(Weight::from_parts(0, 2686).saturating_mul(r.into()))
				.saturating_add(Weight::from_parts(0, 2612).saturating_mul(s.into()))
		}
	}
