
//! Autogenerated weights for `pallet_ethereum_verifier`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-04-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_ethereum_verifier
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_ethereum_verifier`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_ethereum_verifier::WeightInfo for WeightInfo<T> {
	/// Storage: `EthereumVerifier::FinalizedBeaconStateIndex` (r:1 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconStateIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconStateMapping` (r:1 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconStateMapping` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::NextSyncCommittee` (r:0 w:1)
	/// Proof: `EthereumVerifier::NextSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92372), added: 92867, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ForkVersionSchedule` (r:0 w:1)
	/// Proof: `EthereumVerifier::ForkVersionSchedule` (`max_values`: Some(1), `max_size`: Some(84), added: 579, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::InitialCheckpointRoot` (r:0 w:1)
	/// Proof: `EthereumVerifier::InitialCheckpointRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ValidatorsRoot` (r:0 w:1)
	/// Proof: `EthereumVerifier::ValidatorsRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestFinalizedBlockRoot` (r:0 w:1)
	/// Proof: `EthereumVerifier::LatestFinalizedBlockRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::CurrentSyncCommittee` (r:0 w:1)
	/// Proof: `EthereumVerifier::CurrentSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92372), added: 92867, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconState` (r:0 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconState` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn force_checkpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3501`
		// Minimum execution time: 65_415_000_000 picoseconds.
		Weight::from_parts(65_894_000_000, 3501)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(9))
		}
	/// Storage: `EthereumVerifier::OperatingMode` (r:1 w:0)
	/// Proof: `EthereumVerifier::OperatingMode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestFinalizedBlockRoot` (r:1 w:1)
	/// Proof: `EthereumVerifier::LatestFinalizedBlockRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconState` (r:1 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconState` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::NextSyncCommittee` (r:1 w:0)
	/// Proof: `EthereumVerifier::NextSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92372), added: 92867, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ForkVersionSchedule` (r:1 w:0)
	/// Proof: `EthereumVerifier::ForkVersionSchedule` (`max_values`: Some(1), `max_size`: Some(84), added: 579, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::CurrentSyncCommittee` (r:1 w:0)
	/// Proof: `EthereumVerifier::CurrentSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92372), added: 92867, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ValidatorsRoot` (r:1 w:0)
	/// Proof: `EthereumVerifier::ValidatorsRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestSyncCommitteeUpdatePeriod` (r:1 w:0)
	/// Proof: `EthereumVerifier::LatestSyncCommitteeUpdatePeriod` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconStateIndex` (r:1 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconStateIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconStateMapping` (r:1 w:1)
	/// Proof: `EthereumVerifier::FinalizedBeaconStateMapping` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn submit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `92533`
		//  Estimated: `93857`
		// Minimum execution time: 16_626_000_000 picoseconds.
		Weight::from_parts(16_801_000_000, 93857)
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(4))
		}
	/// Storage: `EthereumVerifier::OperatingMode` (r:1 w:0)
	/// Proof: `EthereumVerifier::OperatingMode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestFinalizedBlockRoot` (r:1 w:0)
	/// Proof: `EthereumVerifier::LatestFinalizedBlockRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconState` (r:1 w:0)
	/// Proof: `EthereumVerifier::FinalizedBeaconState` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::NextSyncCommittee` (r:1 w:1)
	/// Proof: `EthereumVerifier::NextSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92372), added: 92867, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ForkVersionSchedule` (r:1 w:0)
	/// Proof: `EthereumVerifier::ForkVersionSchedule` (`max_values`: Some(1), `max_size`: Some(84), added: 579, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::CurrentSyncCommittee` (r:1 w:0)
	/// Proof: `EthereumVerifier::CurrentSyncCommittee` (`max_values`: Some(1), `max_size`: Some(92372), added: 92867, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ValidatorsRoot` (r:1 w:0)
	/// Proof: `EthereumVerifier::ValidatorsRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestSyncCommitteeUpdatePeriod` (r:1 w:1)
	/// Proof: `EthereumVerifier::LatestSyncCommitteeUpdatePeriod` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn submit_with_sync_committee() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `92603`
		//  Estimated: `93857`
		// Minimum execution time: 82_849_000_000 picoseconds.
		Weight::from_parts(84_303_000_000, 93857)
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `EthereumVerifier::OperatingMode` (r:1 w:0)
	/// Proof: `EthereumVerifier::OperatingMode` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ExecutionHeaderAnchors` (r:1 w:1)
	/// Proof: `EthereumVerifier::ExecutionHeaderAnchors` (`max_values`: None, `max_size`: Some(136), added: 2611, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::LatestFinalizedBlockRoot` (r:1 w:0)
	/// Proof: `EthereumVerifier::LatestFinalizedBlockRoot` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::FinalizedBeaconState` (r:1 w:0)
	/// Proof: `EthereumVerifier::FinalizedBeaconState` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ExecutionHeaderAnchorIndex` (r:1 w:1)
	/// Proof: `EthereumVerifier::ExecutionHeaderAnchorIndex` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EthereumVerifier::ExecutionHeaderAnchorMapping` (r:1 w:1)
	/// Proof: `EthereumVerifier::ExecutionHeaderAnchorMapping` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn import_execution_header_anchor() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3601`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(77_000_000, 3601)
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	fn provider_verify_event_log() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `70`
		//  Estimated: `2547`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 2547)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	}
