
//! Autogenerated weights for `pallet_chain_transfer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-02-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_chain_transfer
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_chain_transfer`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_chain_transfer::WeightInfo for WeightInfo<T> {
	/// Storage: `ChainTransfer::NextTransferId` (r:1 w:1)
	/// Proof: `ChainTransfer::NextTransferId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ChainTransfer::PendingTransfersOut` (r:1 w:1)
	/// Proof: `ChainTransfer::PendingTransfersOut` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ChainTransfer::ExpiringTransfersOutByNotary` (r:1 w:1)
	/// Proof: `ChainTransfer::ExpiringTransfersOutByNotary` (`max_values`: None, `max_size`: Some(4030), added: 6505, mode: `MaxEncodedLen`)
	fn send_to_localchain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `7495`
		// Minimum execution time: 54_000_000 picoseconds.
		Weight::from_parts(58_000_000, 7495)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
		}
	/// Storage: `ChainTransfer::PendingTransfersOut` (r:1 w:0)
	/// Proof: `ChainTransfer::PendingTransfersOut` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn provider_is_valid_transfer_to_localchain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `3545`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 3545)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `ChainTransfer::PendingTransfersOut` (r:999 w:999)
	/// Proof: `ChainTransfer::PendingTransfersOut` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `ChainTransfer::ExpiringTransfersOutByNotary` (r:2 w:1)
	/// Proof: `ChainTransfer::ExpiringTransfersOutByNotary` (`max_values`: None, `max_size`: Some(4030), added: 6505, mode: `MaxEncodedLen`)
	/// The range of component `t` is `[1, 1000]`.
	fn notebook_submitted_event_handler(t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3 + t * (90 +/- 0)`
		//  Estimated: `14000 + t * (2555 +/- 0)`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 14000)
			// Standard Error: 65_183
			.saturating_add(Weight::from_parts(7_113_023, 0).saturating_mul(t.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
				.saturating_add(Weight::from_parts(0, 2555).saturating_mul(t.into()))
		}
	/// Storage: `ChainTransfer::ExpiringTransfersOutByNotary` (r:1000 w:999)
	/// Proof: `ChainTransfer::ExpiringTransfersOutByNotary` (`max_values`: None, `max_size`: Some(4030), added: 6505, mode: `MaxEncodedLen`)
	/// Storage: `ChainTransfer::PendingTransfersOut` (r:999 w:999)
	/// Proof: `ChainTransfer::PendingTransfersOut` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1000 w:1000)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[1, 1000]`.
	fn process_expired_transfers(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `37 + e * (111 +/- 0)`
		//  Estimated: `7495 + e * (6505 +/- 0)`
		// Minimum execution time: 53_000_000 picoseconds.
		Weight::from_parts(54_000_000, 7495)
			// Standard Error: 308_779
			.saturating_add(Weight::from_parts(52_991_755, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(e.into())))
				.saturating_add(Weight::from_parts(0, 6505).saturating_mul(e.into()))
		}
	}
