
//! Autogenerated weights for `pallet_operational_accounts`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-06-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_operational_accounts
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_operational_accounts`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_operational_accounts::WeightInfo for WeightInfo<T> {
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:3 w:2)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::IsOperationalAccountInviteOnly` (r:1 w:0)
	/// Proof: `OperationalAccounts::IsOperationalAccountInviteOnly` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5`
		//  Estimated: `8655`
		// Minimum execution time: 119_000_000 picoseconds.
		Weight::from_parts(124_000_000, 8655)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	fn on_vault_created() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `3779`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3779)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn on_vault_bitcoin_lock_funded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `6568`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 6568)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn on_mining_seat_won() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `6568`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 6568)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	fn on_account_bitcoin_amount_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3779`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 3779)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn on_account_vault_bond_total_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `6568`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 6568)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn on_account_uniswap_argon_transfers_in_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `6568`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 6568)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:3 w:2)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::Rewards` (r:1 w:0)
	/// Proof: `OperationalAccounts::Rewards` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn activate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `693`
		//  Estimated: `9357`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 9357)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `OperationalAccounts::Rewards` (r:0 w:1)
	/// Proof: `OperationalAccounts::Rewards` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_reward_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::OperationalAccountBySubAccount` (r:1 w:0)
	/// Proof: `OperationalAccounts::OperationalAccountBySubAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `6568`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 6568)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:1 w:1)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	fn force_set_progress() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3779`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3779)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `OperationalAccounts::OperationalAccounts` (r:2 w:0)
	/// Proof: `OperationalAccounts::OperationalAccounts` (`max_values`: None, `max_size`: Some(314), added: 2789, mode: `MaxEncodedLen`)
	/// Storage: `OperationalAccounts::EncryptedServerByDownstreamAccount` (r:0 w:1)
	/// Proof: `OperationalAccounts::EncryptedServerByDownstreamAccount` (`max_values`: None, `max_size`: Some(306), added: 2781, mode: `MaxEncodedLen`)
	fn set_encrypted_server_for_downstream_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `395`
		//  Estimated: `6568`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 6568)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	}
