
//! Autogenerated weights for `pallet_treasury`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-03-29, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_treasury
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_treasury`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_treasury::WeightInfo for WeightInfo<T> {
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::FunderStateByVaultAndAccount` (r:1 w:1)
	/// Proof: `Treasury::FunderStateByVaultAndAccount` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingUnlocksByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingUnlocksByFrame` (`max_values`: None, `max_size`: Some(36018), added: 38493, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::FundersByVaultId` (r:1 w:1)
	/// Proof: `Treasury::FundersByVaultId` (`max_values`: None, `max_size`: Some(5054), added: 7529, mode: `MaxEncodedLen`)
	fn set_allocation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40911`
		//  Estimated: `39483`
		// Minimum execution time: 102_000_000 picoseconds.
		Weight::from_parts(124_000_000, 39483)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
		}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn try_pay_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `6196`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(44_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `System::Account` (r:1001 w:1001)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn pay_operational_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `2606593`
		// Minimum execution time: 73_721_000_000 picoseconds.
		Weight::from_parts(74_650_000_000, 2606593)
			.saturating_add(T::DbWeight::get().reads(1001))
			.saturating_add(T::DbWeight::get().writes(1001))
		}
	/// Storage: `Treasury::FunderStateByVaultAndAccount` (r:1 w:0)
	/// Proof: `Treasury::FunderStateByVaultAndAccount` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	fn provider_has_pool_participation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `66`
		//  Estimated: `3598`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 3598)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Treasury::PendingUnlockRetryCursor` (r:1 w:0)
	/// Proof: `Treasury::PendingUnlockRetryCursor` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingUnlocksByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingUnlocksByFrame` (`max_values`: None, `max_size`: Some(36018), added: 38493, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::FunderStateByVaultAndAccount` (r:1000 w:1000)
	/// Proof: `Treasury::FunderStateByVaultAndAccount` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1000 w:1000)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1000 w:1000)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::FundersByVaultId` (r:1000 w:1000)
	/// Proof: `Treasury::FundersByVaultId` (`max_values`: None, `max_size`: Some(5054), added: 7529, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::VaultPoolsByFrame` (r:0 w:1)
	/// Proof: `Treasury::VaultPoolsByFrame` (`max_values`: None, `max_size`: Some(482718), added: 485193, mode: `MaxEncodedLen`)
	fn release_pending_unlocks() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `321568`
		//  Estimated: `7529990`
		// Minimum execution time: 54_089_000_000 picoseconds.
		Weight::from_parts(55_155_000_000, 7529990)
			.saturating_add(T::DbWeight::get().reads(4002))
			.saturating_add(T::DbWeight::get().writes(4002))
		}
	/// Storage: `System::Account` (r:9902 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::VaultPoolsByFrame` (r:1 w:1)
	/// Proof: `Treasury::VaultPoolsByFrame` (`max_values`: None, `max_size`: Some(482718), added: 485193, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CapitalActive` (r:1 w:1)
	/// Proof: `Treasury::CapitalActive` (`max_values`: Some(1), `max_size`: Some(2802), added: 3297, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::FunderStateByVaultAndAccount` (r:9900 w:0)
	/// Proof: `Treasury::FunderStateByVaultAndAccount` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	fn distribute_bid_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1044581`
		//  Estimated: `25820190`
		// Minimum execution time: 101_435_000_000 picoseconds.
		Weight::from_parts(104_292_000_000, 25820190)
			.saturating_add(T::DbWeight::get().reads(19804))
			.saturating_add(T::DbWeight::get().writes(4))
		}
	/// Storage: `Treasury::FundersByVaultId` (r:101 w:0)
	/// Proof: `Treasury::FundersByVaultId` (`max_values`: None, `max_size`: Some(5054), added: 7529, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CapitalActive` (r:0 w:1)
	/// Proof: `Treasury::CapitalActive` (`max_values`: Some(1), `max_size`: Some(2802), added: 3297, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::VaultPoolsByFrame` (r:0 w:1)
	/// Proof: `Treasury::VaultPoolsByFrame` (`max_values`: None, `max_size`: Some(482718), added: 485193, mode: `MaxEncodedLen`)
	fn lock_in_vault_capital() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507672`
		//  Estimated: `761419`
		// Minimum execution time: 28_339_000_000 picoseconds.
		Weight::from_parts(29_336_000_000, 761419)
			.saturating_add(T::DbWeight::get().reads(101))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `Treasury::PendingUnlockRetryCursor` (r:1 w:0)
	/// Proof: `Treasury::PendingUnlockRetryCursor` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingUnlocksByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingUnlocksByFrame` (`max_values`: None, `max_size`: Some(36018), added: 38493, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::FunderStateByVaultAndAccount` (r:10900 w:1000)
	/// Proof: `Treasury::FunderStateByVaultAndAccount` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:10902 w:1002)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1000 w:1000)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(175), added: 2650, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::FundersByVaultId` (r:1101 w:1000)
	/// Proof: `Treasury::FundersByVaultId` (`max_values`: None, `max_size`: Some(5054), added: 7529, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::VaultPoolsByFrame` (r:1 w:3)
	/// Proof: `Treasury::VaultPoolsByFrame` (`max_values`: None, `max_size`: Some(482718), added: 485193, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CapitalActive` (r:1 w:1)
	/// Proof: `Treasury::CapitalActive` (`max_values`: Some(1), `max_size`: Some(2802), added: 3297, mode: `MaxEncodedLen`)
	fn on_frame_transition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1872525`
		//  Estimated: `28428190`
		// Minimum execution time: 332_879_000_000 picoseconds.
		Weight::from_parts(341_321_000_000, 28428190)
			.saturating_add(T::DbWeight::get().reads(23907))
			.saturating_add(T::DbWeight::get().writes(4007))
		}
	}
