
//! Autogenerated weights for `pallet_treasury`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-09-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `mac`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/Users/blakebyrnes/.codex/worktrees/d2c4/mainchain/target/bench-build/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_treasury
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_treasury`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_treasury::WeightInfo for WeightInfo<T> {
	/// Storage: `Treasury::TotalArgonBondLots` (r:1 w:1)
	/// Proof: `Treasury::TotalArgonBondLots` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::LastBonusApprovalNonceByVaultAndAccount` (r:1 w:1)
	/// Proof: `Treasury::LastBonusApprovalNonceByVaultAndAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(10058), added: 10553, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::NextBondLotId` (r:1 w:1)
	/// Proof: `Treasury::NextBondLotId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:2 w:1)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:0 w:1)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:0 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	fn buy_bonds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1015`
		//  Estimated: `11543`
		// Minimum execution time: 77_000_000 picoseconds.
		Weight::from_parts(86_000_000, 11543)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(8))
		}
	/// Storage: `Treasury::TotalActiveArgonotBonds` (r:1 w:1)
	/// Proof: `Treasury::TotalActiveArgonotBonds` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::ArgonotBondLots` (r:1 w:1)
	/// Proof: `Treasury::ArgonotBondLots` (`max_values`: Some(1), `max_size`: Some(12002), added: 12497, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::NextBondLotId` (r:1 w:1)
	/// Proof: `Treasury::NextBondLotId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Holds` (r:1 w:1)
	/// Proof: `Ownership::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:1 w:1)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleasesByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingBondReleasesByFrame` (`max_values`: None, `max_size`: Some(8018), added: 10493, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1 w:2)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:0 w:1)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn buy_argonot_bonds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7213`
		//  Estimated: `13487`
		// Minimum execution time: 162_000_000 picoseconds.
		Weight::from_parts(184_000_000, 13487)
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(9))
		}
	/// Storage: `Treasury::BondLotById` (r:1 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::ArgonotBondLots` (r:1 w:1)
	/// Proof: `Treasury::ArgonotBondLots` (`max_values`: Some(1), `max_size`: Some(12002), added: 12497, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TotalActiveArgonotBonds` (r:1 w:1)
	/// Proof: `Treasury::TotalActiveArgonotBonds` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleasesByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingBondReleasesByFrame` (`max_values`: None, `max_size`: Some(8018), added: 10493, mode: `MaxEncodedLen`)
	fn liquidate_bond_lot() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4227`
		//  Estimated: `13487`
		// Minimum execution time: 76_000_000 picoseconds.
		Weight::from_parts(94_000_000, 13487)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
		}
	/// Storage: `Treasury::BondLotById` (r:1 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(10058), added: 10553, mode: `MaxEncodedLen`)
	fn set_bond_lot_flexible() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `11543`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 11543)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn set_reserved_bond_space() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `3502`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3502)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::TargetBitcoinPercent` (r:0 w:1)
	/// Proof: `Treasury::TargetBitcoinPercent` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn configure_reward_economics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::BondLotById` (r:1 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `MiningSlot::NextFrameId` (r:1 w:0)
	/// Proof: `MiningSlot::NextFrameId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn backfill_bond_lot_earnings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `212`
		//  Estimated: `3602`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3602)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `6196`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(36_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `Treasury::BondLotIdsByAccount` (r:1 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn provider_has_vault_bond_participation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `939`
		//  Estimated: `3521`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 3521)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Treasury::BondLotIdsByAccount` (r:1 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn provider_active_vault_bond_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `939`
		//  Estimated: `3521`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(6_000_000, 3521)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Treasury::BondLotIdsByAccount` (r:1 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn provider_active_account_vault_bond_amount() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `939`
		//  Estimated: `3521`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 3521)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `Treasury::EncumberedBondMicrogonsByAccount` (r:1 w:1)
	/// Proof: `Treasury::EncumberedBondMicrogonsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:2 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1 w:0)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	fn provider_encumber_bond_microgons() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `6052`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 6052)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::EncumberedBondMicrogonsByAccount` (r:1 w:1)
	/// Proof: `Treasury::EncumberedBondMicrogonsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:2 w:0)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1 w:0)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	fn provider_release_encumbered_bond_microgons() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `6052`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(18_000_000, 6052)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::EncumberedBondMicrogonsByAccount` (r:1 w:1)
	/// Proof: `Treasury::EncumberedBondMicrogonsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:2 w:1)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1 w:1)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TotalArgonBondLots` (r:1 w:1)
	/// Proof: `Treasury::TotalArgonBondLots` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:1 w:1)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:0)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(10058), added: 10553, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:0 w:1)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn provider_burn_encumbered_bond_microgons() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `436`
		//  Estimated: `11543`
		// Minimum execution time: 64_000_000 picoseconds.
		Weight::from_parts(66_000_000, 11543)
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(8))
		}
	/// Storage: `Treasury::PendingBondReleaseRetryCursor` (r:1 w:0)
	/// Proof: `Treasury::PendingBondReleaseRetryCursor` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleasesByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingBondReleasesByFrame` (`max_values`: None, `max_size`: Some(8018), added: 10493, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:1000 w:1000)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1000 w:1000)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1000 w:1000)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TotalArgonBondLots` (r:1 w:1)
	/// Proof: `Treasury::TotalArgonBondLots` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:0 w:1000)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:0 w:1000)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn release_pending_bond_lots() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `298816`
		//  Estimated: `2668990`
		// Minimum execution time: 46_195_000_000 picoseconds.
		Weight::from_parts(50_927_000_000, 2668990)
			.saturating_add(T::DbWeight::get().reads(3003))
			.saturating_add(T::DbWeight::get().writes(5002))
		}
	/// Storage: `Treasury::CurrentFrameArgonotBondParticipants` (r:1 w:1)
	/// Proof: `Treasury::CurrentFrameArgonotBondParticipants` (`max_values`: Some(1), `max_size`: Some(12014), added: 12509, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:1)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(10058), added: 10553, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:11202 w:11202)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:13600 w:13600)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:12601 w:0)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:100 w:0)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn distribute_bid_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1358895`
		//  Estimated: `35524190`
		// Minimum execution time: 665_667_000_000 picoseconds.
		Weight::from_parts(672_156_000_000, 35524190)
			.saturating_add(T::DbWeight::get().reads(37505))
			.saturating_add(T::DbWeight::get().writes(24804))
		}
	/// Storage: `Treasury::BondLotsByVault` (r:102 w:0)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Mint::MintedBitcoinMicrogons` (r:1 w:0)
	/// Proof: `Mint::MintedBitcoinMicrogons` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TargetBitcoinPercent` (r:1 w:0)
	/// Proof: `Treasury::TargetBitcoinPercent` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:0 w:1)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(10058), added: 10553, mode: `MaxEncodedLen`)
	fn lock_in_vault_capital() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2435`
		//  Estimated: `257214`
		// Minimum execution time: 555_000_000 picoseconds.
		Weight::from_parts(582_000_000, 257214)
			.saturating_add(T::DbWeight::get().reads(104))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `Treasury::CurrentFrameArgonotBondParticipants` (r:1 w:1)
	/// Proof: `Treasury::CurrentFrameArgonotBondParticipants` (`max_values`: Some(1), `max_size`: Some(12014), added: 12509, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::CurrentFrameVaultCapital` (r:1 w:1)
	/// Proof: `Treasury::CurrentFrameVaultCapital` (`max_values`: Some(1), `max_size`: Some(10058), added: 10553, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:17002 w:17002)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotById` (r:17000 w:17000)
	/// Proof: `Treasury::BondLotById` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByVault` (r:16001 w:1000)
	/// Proof: `Treasury::BondLotIdsByVault` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotsByVault` (r:102 w:0)
	/// Proof: `Treasury::BondLotsByVault` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleaseRetryCursor` (r:1 w:0)
	/// Proof: `Treasury::PendingBondReleaseRetryCursor` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::PendingBondReleasesByFrame` (r:1 w:1)
	/// Proof: `Treasury::PendingBondReleasesByFrame` (`max_values`: None, `max_size`: Some(8018), added: 10493, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1000 w:1000)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(193), added: 2668, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TotalArgonBondLots` (r:1 w:1)
	/// Proof: `Treasury::TotalArgonBondLots` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::ArgonotBondLots` (r:1 w:0)
	/// Proof: `Treasury::ArgonotBondLots` (`max_values`: Some(1), `max_size`: Some(12002), added: 12497, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TotalActiveArgonotBonds` (r:1 w:0)
	/// Proof: `Treasury::TotalActiveArgonotBonds` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Mint::MintedBitcoinMicrogons` (r:1 w:0)
	/// Proof: `Mint::MintedBitcoinMicrogons` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::TargetBitcoinPercent` (r:1 w:0)
	/// Proof: `Treasury::TargetBitcoinPercent` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Treasury::BondLotIdsByAccount` (r:0 w:1000)
	/// Proof: `Treasury::BondLotIdsByAccount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[0, 15000]`.
	/// The range of component `s` is `[0, 1000]`.
	/// The range of component `r` is `[0, 1000]`.
	/// Regression samples use up to 3,000 bonds, 200 stakes, and 200 releases; the full-cap
	/// 15,000/1,000/1,000 path was also measured directly.
	fn on_frame_transition(b: u32, s: u32, r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9316 + b * (91 +/- 0) + r * (331 +/- 0) + s * (207 +/- 0)`
		//  Estimated: `257214 + b * (2612 +/- 0) + r * (2686 +/- 0) + s * (2612 +/- 0)`
		// Minimum execution time: 29_059_000_000 picoseconds.
		// Retain the larger previous fixed and component estimates where the measured regression
		// would otherwise reduce them. Bond recipients are distinct in this benchmark.
		Weight::from_parts(113_602_000_000, 266496)
			.saturating_add(Weight::from_parts(48_241_288, 0).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(43_849_999, 0).saturating_mul(s.into()))
			.saturating_add(Weight::from_parts(93_268_230, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(214))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(106))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes((5_u64).saturating_mul(r.into())))
				.saturating_add(Weight::from_parts(0, 2612).saturating_mul(b.into()))
				.saturating_add(Weight::from_parts(0, 2686).saturating_mul(r.into()))
				.saturating_add(Weight::from_parts(0, 2635).saturating_mul(s.into()))
		}
	}
