
//! Autogenerated weights for `pallet_crosschain_transfer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-06-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_crosschain_transfer
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_crosschain_transfer`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_crosschain_transfer::WeightInfo for WeightInfo<T> {
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn set_chain_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `85`
		//  Estimated: `3593`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `CrosschainTransfer::GatewayStateBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewayStateBySourceChain` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PendingCouncilSignerByDestinationChainAndAccountId` (r:1 w:0)
	/// Proof: `CrosschainTransfer::PendingCouncilSignerByDestinationChainAndAccountId` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilSignerByDestinationChainAndAccountId` (r:1 w:0)
	/// Proof: `CrosschainTransfer::CouncilSignerByDestinationChainAndAccountId` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ActiveGlobalIssuanceCouncilByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::ActiveGlobalIssuanceCouncilByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GlobalIssuanceCouncilByHash` (r:2 w:2)
	/// Proof: `CrosschainTransfer::GlobalIssuanceCouncilByHash` (`max_values`: None, `max_size`: Some(8882), added: 11357, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilApprovalCursorByDestinationChainAndAccountId` (r:1 w:1)
	/// Proof: `CrosschainTransfer::CouncilApprovalCursorByDestinationChainAndAccountId` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::NextCouncilApprovalQueueNonceByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::NextCouncilApprovalQueueNonceByDestinationChain` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (r:2 w:2)
	/// Proof: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (`max_values`: None, `max_size`: Some(8720), added: 11195, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::MintingAuthoritiesBySigner` (r:1 w:1)
	/// Proof: `CrosschainTransfer::MintingAuthoritiesBySigner` (`max_values`: None, `max_size`: Some(3405), added: 5880, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (r:0 w:1)
	/// Proof: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::LatestQueuedCouncilHashByDestinationChain` (r:0 w:1)
	/// Proof: `CrosschainTransfer::LatestQueuedCouncilHashByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn force_set_global_issuance_council() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1434`
		//  Estimated: `23704`
		// Minimum execution time: 93_000_000 picoseconds.
		Weight::from_parts(100_000_000, 23704)
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(10))
		}
	/// Storage: `CrosschainTransfer::GatewayStateBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewayStateBySourceChain` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (r:0 w:1)
	/// Proof: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	fn pause_gateway() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `57`
		//  Estimated: `3530`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 3530)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	fn unpause_gateway() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `24`
		//  Estimated: `3499`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 3499)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `CrosschainTransfer::CouncilSignerByDestinationChainAndAccountId` (r:1 w:1)
	/// Proof: `CrosschainTransfer::CouncilSignerByDestinationChainAndAccountId` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn register_council_signer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3550`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3550)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::MintingAuthoritiesBySigner` (r:1 w:1)
	/// Proof: `CrosschainTransfer::MintingAuthoritiesBySigner` (`max_values`: None, `max_size`: Some(3405), added: 5880, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::MinimumMintingAuthorityValueByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::MinimumMintingAuthorityValueByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::NextCouncilApprovalQueueNonceByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::NextCouncilApprovalQueueNonceByDestinationChain` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::LatestQueuedCouncilHashByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::LatestQueuedCouncilHashByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ActiveGlobalIssuanceCouncilByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ActiveGlobalIssuanceCouncilByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::MintingAuthorityActivationRepaymentPricingByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::MintingAuthorityActivationRepaymentPricingByDestinationChain` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GlobalIssuanceCouncilByHash` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GlobalIssuanceCouncilByHash` (`max_values`: None, `max_size`: Some(8882), added: 11357, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GatewayStateBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewayStateBySourceChain` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (r:0 w:1)
	/// Proof: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (`max_values`: None, `max_size`: Some(8720), added: 11195, mode: `MaxEncodedLen`)
	fn register_minting_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `511`
		//  Estimated: `12347`
		// Minimum execution time: 89_000_000 picoseconds.
		Weight::from_parts(96_000_000, 12347)
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(6))
		}
	/// Storage: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GatewayStateBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewayStateBySourceChain` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilApprovalCursorByDestinationChainAndAccountId` (r:1 w:1)
	/// Proof: `CrosschainTransfer::CouncilApprovalCursorByDestinationChainAndAccountId` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (r:32 w:32)
	/// Proof: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (`max_values`: None, `max_size`: Some(8720), added: 11195, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GlobalIssuanceCouncilByHash` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GlobalIssuanceCouncilByHash` (`max_values`: None, `max_size`: Some(8882), added: 11357, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[1, 32]`.
	fn approve_queue_entries(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `442 + a * (191 +/- 0)`
		//  Estimated: `12347 + a * (11195 +/- 0)`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(19_644_712, 12347)
			// Standard Error: 36_342
			.saturating_add(Weight::from_parts(13_298_582, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
				.saturating_add(Weight::from_parts(0, 11195).saturating_mul(a.into()))
		}
	/// Storage: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GatewayStateBySourceChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::GatewayStateBySourceChain` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PendingTransferOutCirculationByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::PendingTransferOutCirculationByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:111 w:111)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:1 w:0)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::RecentArgonTransfersByAccount` (r:10 w:10)
	/// Proof: `CrosschainTransfer::RecentArgonTransfersByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Ticks::CurrentTick` (r:1 w:0)
	/// Proof: `Ticks::CurrentTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::InboundTransfersExpiringAt` (r:1 w:1)
	/// Proof: `CrosschainTransfer::InboundTransfersExpiringAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CrosschainTransfer::TransferOutById` (r:101 w:100)
	/// Proof: `CrosschainTransfer::TransferOutById` (`max_values`: None, `max_size`: Some(13485), added: 15960, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PendingCollateralizationRequestsByChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::PendingCollateralizationRequestsByChain` (`max_values`: None, `max_size`: Some(6419), added: 8894, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::NonTerminalTransferOutCountByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::NonTerminalTransferOutCountByDestinationChain` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::MintingAuthoritiesBySigner` (r:1 w:1)
	/// Proof: `CrosschainTransfer::MintingAuthoritiesBySigner` (`max_values`: None, `max_size`: Some(3405), added: 5880, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:100 w:100)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ActiveGlobalIssuanceCouncilByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ActiveGlobalIssuanceCouncilByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::NextCouncilApprovalQueueNonceByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::NextCouncilApprovalQueueNonceByDestinationChain` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (r:0 w:1)
	/// Proof: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::LatestQueuedCouncilHashByDestinationChain` (r:0 w:1)
	/// Proof: `CrosschainTransfer::LatestQueuedCouncilHashByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[1, 10]`.
	fn prove_gateway_activity(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `54491`
		//  Estimated: `1612950 + a * (2603 +/- 0)`
		// Minimum execution time: 8_898_000_000 picoseconds.
		Weight::from_parts(9_086_552_249, 1612950)
			// Standard Error: 1_475_179
			.saturating_add(Weight::from_parts(216_448_157, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(316))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(309))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(a.into())))
				.saturating_add(Weight::from_parts(0, 2603).saturating_mul(a.into()))
		}
	/// Storage: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `Ticks::CurrentTick` (r:1 w:0)
	/// Proof: `Ticks::CurrentTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::NonTerminalTransferOutCountByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::NonTerminalTransferOutCountByDestinationChain` (`max_values`: None, `max_size`: Some(21), added: 2496, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::NextTransferOutNonceBySendingAccountId` (r:1 w:1)
	/// Proof: `CrosschainTransfer::NextTransferOutNonceBySendingAccountId` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PendingTransferOutCirculationByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::PendingTransferOutCirculationByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PendingCollateralizationRequestsByChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::PendingCollateralizationRequestsByChain` (`max_values`: None, `max_size`: Some(6419), added: 8894, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::TransferOutById` (r:0 w:1)
	/// Proof: `CrosschainTransfer::TransferOutById` (`max_values`: None, `max_size`: Some(13485), added: 15960, mode: `MaxEncodedLen`)
	fn transfer_out() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `312`
		//  Estimated: `9884`
		// Minimum execution time: 100_000_000 picoseconds.
		Weight::from_parts(104_000_000, 9884)
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(7))
		}
	/// Storage: `CrosschainTransfer::TransferOutById` (r:1 w:1)
	/// Proof: `CrosschainTransfer::TransferOutById` (`max_values`: None, `max_size`: Some(13485), added: 15960, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::MintingAuthoritiesBySigner` (r:1 w:1)
	/// Proof: `CrosschainTransfer::MintingAuthoritiesBySigner` (`max_values`: None, `max_size`: Some(3405), added: 5880, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PendingCollateralizationRequestsByChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::PendingCollateralizationRequestsByChain` (`max_values`: None, `max_size`: Some(6419), added: 8894, mode: `MaxEncodedLen`)
	fn collateralize_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `778`
		//  Estimated: `16950`
		// Minimum execution time: 32_000_000 picoseconds.
		Weight::from_parts(33_000_000, 16950)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `CrosschainTransfer::MintingAuthoritiesBySigner` (r:1 w:1)
	/// Proof: `CrosschainTransfer::MintingAuthoritiesBySigner` (`max_values`: None, `max_size`: Some(3405), added: 5880, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::LatestQueuedCouncilHashByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::LatestQueuedCouncilHashByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ActiveGlobalIssuanceCouncilByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ActiveGlobalIssuanceCouncilByDestinationChain` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::NextCouncilApprovalQueueNonceByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::NextCouncilApprovalQueueNonceByDestinationChain` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (r:1 w:1)
	/// Proof: `CrosschainTransfer::TransferOutQuoteMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::CurrentTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::PreviousTransferOutMicrogonsPerArgonotByDestinationChain` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GlobalIssuanceCouncilByHash` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GlobalIssuanceCouncilByHash` (`max_values`: None, `max_size`: Some(8882), added: 11357, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (r:0 w:1)
	/// Proof: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (`max_values`: None, `max_size`: Some(8720), added: 11195, mode: `MaxEncodedLen`)
	fn deactivate_minting_authority() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `632`
		//  Estimated: `12347`
		// Minimum execution time: 42_000_000 picoseconds.
		Weight::from_parts(44_000_000, 12347)
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(5))
		}
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:1 w:0)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `Ticks::CurrentTick` (r:1 w:0)
	/// Proof: `Ticks::CurrentTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::LastTransferExpiryCleanupTick` (r:1 w:1)
	/// Proof: `CrosschainTransfer::LastTransferExpiryCleanupTick` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::InboundTransfersExpiringAt` (r:1 w:1)
	/// Proof: `CrosschainTransfer::InboundTransfersExpiringAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CrosschainTransfer::RecentArgonTransfersByAccount` (r:999 w:999)
	/// Proof: `CrosschainTransfer::RecentArgonTransfersByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `e` is `[1, 1000]`.
	fn on_initialize_cleanup(e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `63 + e * (89 +/- 0)`
		//  Estimated: `3593 + e * (2527 +/- 0)`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3593)
			// Standard Error: 4_931
			.saturating_add(Weight::from_parts(3_783_408, 0).saturating_mul(e.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(e.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(e.into())))
				.saturating_add(Weight::from_parts(0, 2527).saturating_mul(e.into()))
		}
	/// Storage: `CrosschainTransfer::ChainConfigBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::ChainConfigBySourceChain` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewaySyncPauseBySourceChain` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	fn provider_is_crosschain_activated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `53`
		//  Estimated: `3551`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 3551)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	/// Storage: `CrosschainTransfer::RecentArgonTransfersByAccount` (r:1 w:0)
	/// Proof: `CrosschainTransfer::RecentArgonTransfersByAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn provider_has_recent_argon_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `57`
		//  Estimated: `3517`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(3_000_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1))
		}
	/// Storage: `CrosschainTransfer::GatewayStateBySourceChain` (r:1 w:0)
	/// Proof: `CrosschainTransfer::GatewayStateBySourceChain` (`max_values`: None, `max_size`: Some(65), added: 2540, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilApprovalCursorByDestinationChainAndAccountId` (r:1 w:0)
	/// Proof: `CrosschainTransfer::CouncilApprovalCursorByDestinationChainAndAccountId` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (r:1 w:0)
	/// Proof: `CrosschainTransfer::CouncilApprovalQueueByDestinationChainAndNonce` (`max_values`: None, `max_size`: Some(8720), added: 11195, mode: `MaxEncodedLen`)
	fn provider_has_overdue_collect_blocker() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `473`
		//  Estimated: `12185`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 12185)
			.saturating_add(T::DbWeight::get().reads(3))
		}
	}
