
//! Autogenerated weights for `pallet_bitcoin_fissions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-08-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_bitcoin_fissions
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=20
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_bitcoin_fissions`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_bitcoin_fissions::WeightInfo for WeightInfo<T> {
	/// Storage: `BitcoinFissions::NextFissionIdByOwner` (r:1 w:1)
	/// Proof: `BitcoinFissions::NextFissionIdByOwner` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinFissions::FissionByOwnerAndId` (r:1 w:1)
	/// Proof: `BitcoinFissions::FissionByOwnerAndId` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinFissions::FissionIdsByLockId` (r:1 w:1)
	/// Proof: `BitcoinFissions::FissionIdsByLockId` (`max_values`: None, `max_size`: Some(417), added: 2892, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3882`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 3882)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `BitcoinFissions::FissionByOwnerAndId` (r:1 w:1)
	/// Proof: `BitcoinFissions::FissionByOwnerAndId` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn ratchet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `3605`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 3605)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
		}
	/// Storage: `BitcoinFissions::FissionByOwnerAndId` (r:1 w:1)
	/// Proof: `BitcoinFissions::FissionByOwnerAndId` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinFissions::FissionIdsByLockId` (r:1 w:1)
	/// Proof: `BitcoinFissions::FissionIdsByLockId` (`max_values`: None, `max_size`: Some(417), added: 2892, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `128`
		//  Estimated: `3882`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(32_000_000, 3882)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
		}
	/// Storage: `BitcoinFissions::FissionIdsByLockId` (r:1 w:1)
	/// Proof: `BitcoinFissions::FissionIdsByLockId` (`max_values`: None, `max_size`: Some(417), added: 2892, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinFissions::FissionByOwnerAndId` (r:50 w:50)
	/// Proof: `BitcoinFissions::FissionByOwnerAndId` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[0, 50]`.
	fn lock_spent(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `39 + l * (39 +/- 0)`
		//  Estimated: `3882 + l * (2615 +/- 0)`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(1_343_765, 3882)
			// Standard Error: 13_439
			.saturating_add(Weight::from_parts(5_252_374, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(l.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(l.into())))
				.saturating_add(Weight::from_parts(0, 2615).saturating_mul(l.into()))
		}
	/// Storage: `BitcoinFissions::FissionByOwnerAndId` (r:2 w:0)
	/// Proof: `BitcoinFissions::FissionByOwnerAndId` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	fn provider_get_account_fission_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `6220`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 6220)
			.saturating_add(T::DbWeight::get().reads(2))
		}
	/// Storage: `BitcoinFissions::FissionIdsByLockId` (r:1 w:0)
	/// Proof: `BitcoinFissions::FissionIdsByLockId` (`max_values`: None, `max_size`: Some(417), added: 2892, mode: `MaxEncodedLen`)
	/// Storage: `BitcoinFissions::FissionByOwnerAndId` (r:50 w:0)
	/// Proof: `BitcoinFissions::FissionByOwnerAndId` (`max_values`: None, `max_size`: Some(140), added: 2615, mode: `MaxEncodedLen`)
	fn provider_get_lock_fission_requirements() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1994`
		//  Estimated: `131740`
		// Minimum execution time: 144_000_000 picoseconds.
		Weight::from_parts(157_000_000, 131740)
			.saturating_add(T::DbWeight::get().reads(51))
		}
	}
