
//! Autogenerated weights for `pallet_block_rewards`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2026-06-28, STEPS: `50`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Blakes-M2.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/release/wbuild/argon-canary-runtime/argon_canary_runtime.compact.wasm
// --pallet=pallet_block_rewards
// --extrinsic=*
// --genesis-builder-policy=none
// --template=scripts/weight_template.hbs
// --repeat=10
// --output=runtime/canary/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;
use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_block_rewards`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_block_rewards::WeightInfo for WeightInfo<T> {
	/// Storage: `BlockRewards::BlockRewardsPaused` (r:0 w:1)
	/// Proof: `BlockRewards::BlockRewardsPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_block_rewards_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `BlockRewards::BlockVoterRewardsEnabled` (r:0 w:1)
	/// Proof: `BlockRewards::BlockVoterRewardsEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_block_voter_rewards_enabled() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
		}
	/// Storage: `BlockRewards::BlockRewardsPaused` (r:1 w:0)
	/// Proof: `BlockRewards::BlockRewardsPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `BlockRewards::BlockRewardsByCohort` (r:1 w:0)
	/// Proof: `BlockRewards::BlockRewardsByCohort` (`max_values`: Some(1), `max_size`: Some(265), added: 760, mode: `MaxEncodedLen`)
	/// Storage: `BlockRewards::BlockVoterRewardsEnabled` (r:1 w:0)
	/// Proof: `BlockRewards::BlockVoterRewardsEnabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Ownership::Account` (r:2 w:2)
	/// Proof: `Ownership::Account` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	/// Storage: `BlockRewards::PayoutsByBlock` (r:0 w:1)
	/// Proof: `BlockRewards::PayoutsByBlock` (`max_values`: None, `max_size`: Some(315), added: 2790, mode: `MaxEncodedLen`)
	fn on_initialize_with_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `6196`
		// Minimum execution time: 61_000_000 picoseconds.
		Weight::from_parts(71_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
		}
	}
