name: Install Minio
description: |
  Add Minio to the GitHub runner

runs:
  using: "composite"
  steps:
    - name: Install Minio on Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        arch=$(uname -m)
        if [ "$arch" = "aarch64" ]; then
          url="https://dl.min.io/server/minio/release/linux-arm64/minio"
        else
          url="https://dl.min.io/server/minio/release/linux-amd64/minio"
        fi
        wget "$url"
        chmod +x minio
        sudo mv minio /usr/local/bin

    - name: Install Minio on macOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        arch=$(uname -m)
        if [ "$arch" = "arm64" ]; then
          url="https://dl.min.io/server/minio/release/darwin-arm64/minio"
        else
          url="https://dl.min.io/server/minio/release/darwin-amd64/minio"
        fi
        wget "$url"
        chmod +x minio
        sudo mv minio /usr/local/bin

    - name: Start Minio on Linux and macOS
      shell: bash
      run: |
        mkdir -p /tmp/minio
        nohup minio server /tmp/minio &
