name: Install Minio
description: |
  Add Minio to the GitHub runner

runs:
  using: "composite"
  steps:
    - name: Install Minio on Linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        wget https://dl.min.io/server/minio/release/linux-amd64/minio
        chmod +x minio
        sudo mv minio /usr/local/bin

    - name: Install Minio on macOS
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        wget https://dl.min.io/server/minio/release/darwin-amd64/minio
        chmod +x minio
        sudo mv minio /usr/local/bin

    - name: Start Minio on Linux and macOS
      shell: bash
      run: |
        mkdir -p /tmp/minio
        nohup minio server /tmp/minio &
