name: Install Minio
description: |
  Add Minio to the GitHub runner

runs:
  using: "composite"
  steps:
    - name: Install Minio
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      run: |
        set -eu
        CGO_ENABLED=0 GOBIN="$RUNNER_TEMP/minio-bin" go install github.com/minio/minio@RELEASE.2025-09-07T16-13-09Z
        sudo mv "$RUNNER_TEMP/minio-bin/minio" /usr/local/bin

    - name: Start Minio on Linux and macOS
      shell: bash
      run: |
        mkdir -p /tmp/minio
        nohup minio server /tmp/minio &
