name: Cache rust dependencies
description: |
  Shared config to cache rust dependencies

inputs:
  github-token:
    description: 'The github token'
    required: true
  name:
    description: 'The name of the cache'
    required: true
  save:
    description: 'Whether to save the cache'
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Get rustc version
      id: rust-version
      run: echo "version=$(rustc --version --verbose | grep 'release:' | awk '{print $2}')" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          .cargo-cache
          target/
        key: ${{ inputs.name }}-${{ runner.os }}-${{ steps.rust-version.outputs.version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ inputs.name }}-${{ runner.os }}-${{ steps.rust-version.outputs.version }}-
        save-always: ${{ inputs.save }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
