use pallet_prelude::*;

/// Weight functions needed for pallet_chain_transfer.
pub trait WeightInfo {
	// Actual extrinsics
	fn send_to_localchain() -> Weight;

	// Event handlers and components
	fn notebook_submitted_event_handler(t: u32) -> Weight;
	fn process_expired_transfers(e: u32) -> Weight;
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn send_to_localchain() -> Weight {
		Weight::zero()
	}

	fn notebook_submitted_event_handler(_t: u32) -> Weight {
		Weight::zero()
	}

	fn process_expired_transfers(_e: u32) -> Weight {
		Weight::zero()
	}
}

// NotebookEventHandlerWeightInfo implementation will be generated by runtime
