[profile.ci]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false
retries = { backoff = "exponential", count = 2, delay = "5s", jitter = true }

[profile.default]
retries = { backoff = "exponential", count = 2, delay = "5s", jitter = true }
