//! Autogenerated weights for pallet_bitcoin_locks
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2025-06-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// cargo run --package argon-node --features runtime-benchmarks -- benchmark pallet --pallet pallet_bitcoin_locks --extrinsic "*" --steps 50 --repeat 20

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use super::Config;
use argon_primitives::providers::{
	BitcoinLocksProviderWeightInfo, BitcoinUtxoEventsWeightInfo, UtxoLockEvents,
};
use argon_primitives::UtxoLockEventsWeightInfo;
use pallet_prelude::*;

/// Weight functions needed for pallet_bitcoin_locks.
pub trait WeightInfo {
	// Core extrinsics
	fn initialize() -> Weight;
	fn initialize_for() -> Weight;
	fn request_release() -> Weight;
	fn cosign_release() -> Weight;
	fn ratchet() -> Weight;

	// Hooks with variance
	fn on_initialize_with_expirations_and_overdue(
		expiring_count: u32,
		overdue_count: u32,
		orphan_expiring_count: u32,
	) -> Weight {
		let mut weight = Self::on_initialize_base();
		if expiring_count > 0 {
			weight = weight.saturating_add(Self::on_initialize_expiring_locks(expiring_count));
		}
		if overdue_count > 0 {
			weight = weight.saturating_add(Self::on_initialize_overdue_releases(overdue_count));
		}
		if orphan_expiring_count > 0 {
			weight = weight
				.saturating_add(Self::on_initialize_orphan_expirations(orphan_expiring_count));
		}
		weight
	}
	fn on_initialize_base() -> Weight;
	fn on_initialize_expiring_locks(n: u32) -> Weight;
	fn on_initialize_overdue_releases(n: u32) -> Weight;
	fn on_initialize_orphan_expirations(n: u32) -> Weight;

	// Admin function
	fn admin_modify_minimum_locked_sats() -> Weight;

	// Orphaned Utxo process
	fn request_orphaned_utxo_release() -> Weight;
	fn cosign_orphaned_utxo_release() -> Weight;
	fn increase_securitization() -> Weight;
	fn register_fee_coupon() -> Weight;

	fn provider_get_account_funded_bitcoin_amount() -> Weight;
	// Bitcoin UTXO event handler provider weights
	fn provider_funding_received() -> Weight;
	fn provider_timeout_waiting_for_funding() -> Weight;
	fn provider_funding_promoted_by_account() -> Weight;
	fn provider_candidate_rejected_by_account() -> Weight;
	fn provider_orphaned_utxo_detected() -> Weight;
	fn provider_spent() -> Weight;
}

type LockEventWeights<T> = <<T as Config>::LockEvents as UtxoLockEvents<
	<T as frame_system::Config>::AccountId,
	<T as Config>::Balance,
>>::Weights;

/// Placeholder implementation for tests and no-std environments
pub struct SubstrateWeight<T>(PhantomData<T>);

pub struct WithProviderWeights<T, Base, LockEventWeight = LockEventWeights<T>>(
	PhantomData<(T, Base, LockEventWeight)>,
);
impl<T, Base, LockEventWeight> WeightInfo for WithProviderWeights<T, Base, LockEventWeight>
where
	T: Config,
	Base: WeightInfo,
	LockEventWeight: UtxoLockEventsWeightInfo,
{
	fn initialize() -> Weight {
		Base::initialize()
	}

	fn initialize_for() -> Weight {
		Base::initialize_for()
	}

	fn request_release() -> Weight {
		Base::request_release()
	}

	fn cosign_release() -> Weight {
		Base::cosign_release().saturating_add(LockEventWeight::utxo_released())
	}

	fn ratchet() -> Weight {
		Base::ratchet()
			.saturating_add(LockEventWeight::utxo_locked())
			.saturating_add(LockEventWeight::utxo_released())
	}

	fn on_initialize_base() -> Weight {
		Base::on_initialize_base()
	}

	fn on_initialize_expiring_locks(n: u32) -> Weight {
		Base::on_initialize_expiring_locks(n)
			.saturating_add(LockEventWeight::utxo_released().saturating_mul(n.into()))
	}

	fn on_initialize_overdue_releases(n: u32) -> Weight {
		Base::on_initialize_overdue_releases(n)
			.saturating_add(LockEventWeight::utxo_released().saturating_mul(n.into()))
	}

	fn on_initialize_orphan_expirations(n: u32) -> Weight {
		Base::on_initialize_orphan_expirations(n)
	}

	fn admin_modify_minimum_locked_sats() -> Weight {
		Base::admin_modify_minimum_locked_sats()
	}

	fn request_orphaned_utxo_release() -> Weight {
		Base::request_orphaned_utxo_release()
	}

	fn cosign_orphaned_utxo_release() -> Weight {
		Base::cosign_orphaned_utxo_release()
	}

	fn increase_securitization() -> Weight {
		Base::increase_securitization()
	}

	fn register_fee_coupon() -> Weight {
		Base::register_fee_coupon()
	}

	fn provider_get_account_funded_bitcoin_amount() -> Weight {
		Base::provider_get_account_funded_bitcoin_amount()
	}

	fn provider_funding_received() -> Weight {
		Base::provider_funding_received().saturating_add(LockEventWeight::utxo_locked())
	}

	fn provider_timeout_waiting_for_funding() -> Weight {
		Base::provider_timeout_waiting_for_funding()
	}

	fn provider_funding_promoted_by_account() -> Weight {
		Base::provider_funding_promoted_by_account()
			.saturating_add(LockEventWeight::utxo_locked())
	}

	fn provider_candidate_rejected_by_account() -> Weight {
		Base::provider_candidate_rejected_by_account()
	}

	fn provider_orphaned_utxo_detected() -> Weight {
		Base::provider_orphaned_utxo_detected()
	}

	fn provider_spent() -> Weight {
		Base::provider_spent()
			.saturating_add(LockEventWeight::utxo_released_with_pending_mints())
	}
}

pub struct ProviderWeightAdapter<T>(PhantomData<T>);
impl<T: Config> BitcoinLocksProviderWeightInfo for ProviderWeightAdapter<T> {
	fn get_account_funded_bitcoin_amount() -> Weight {
		<T as Config>::WeightInfo::provider_get_account_funded_bitcoin_amount()
	}
}
impl<T: Config> BitcoinUtxoEventsWeightInfo for ProviderWeightAdapter<T> {
	fn funding_received() -> Weight {
		<T as Config>::WeightInfo::provider_funding_received()
	}

	fn timeout_waiting_for_funding() -> Weight {
		<T as Config>::WeightInfo::provider_timeout_waiting_for_funding()
	}

	fn funding_promoted_by_account() -> Weight {
		<T as Config>::WeightInfo::provider_funding_promoted_by_account()
	}

	fn candidate_rejected_by_account() -> Weight {
		<T as Config>::WeightInfo::provider_candidate_rejected_by_account()
	}

	fn orphaned_utxo_detected() -> Weight {
		<T as Config>::WeightInfo::provider_orphaned_utxo_detected()
	}

	fn spent() -> Weight {
		<T as Config>::WeightInfo::provider_spent()
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn initialize() -> Weight { Weight::zero() }
	fn initialize_for() -> Weight { Weight::zero() }
	fn request_release() -> Weight { Weight::zero() }
	fn cosign_release() -> Weight { Weight::zero() }
	fn ratchet() -> Weight { Weight::zero() }
	fn on_initialize_base() -> Weight { Weight::zero() }
	fn on_initialize_expiring_locks(_n: u32) -> Weight { Weight::zero() }
	fn on_initialize_overdue_releases(_n: u32) -> Weight { Weight::zero() }
	fn on_initialize_orphan_expirations(_n: u32) -> Weight { Weight::zero() }
	fn admin_modify_minimum_locked_sats() -> Weight { Weight::zero() }
	fn request_orphaned_utxo_release() -> Weight { Weight::zero() }
	fn cosign_orphaned_utxo_release() -> Weight { Weight::zero() }
	fn increase_securitization() -> Weight { Weight::zero() }
	fn register_fee_coupon() -> Weight { Weight::zero() }
	fn provider_get_account_funded_bitcoin_amount() -> Weight { Weight::zero() }
	fn provider_funding_received() -> Weight { Weight::zero() }
	fn provider_timeout_waiting_for_funding() -> Weight { Weight::zero() }
	fn provider_funding_promoted_by_account() -> Weight { Weight::zero() }
	fn provider_candidate_rejected_by_account() -> Weight { Weight::zero() }
	fn provider_orphaned_utxo_detected() -> Weight { Weight::zero() }
	fn provider_spent() -> Weight { Weight::zero() }
}
