//! Autogenerated weights for pallet_bitcoin_locks
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2025-06-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// cargo run --package argon-node --features runtime-benchmarks -- benchmark pallet --pallet pallet_bitcoin_locks --extrinsic "*" --steps 50 --repeat 20

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use super::Config;
use argon_primitives::providers::{
	BitcoinFissionLockProviderWeightInfo, BitcoinFissionsProvider, BitcoinFissionsProviderWeightInfo,
	BitcoinUtxoEventsWeightInfo,
};
use argon_primitives::vault::{BitcoinVaultProvider, BitcoinVaultProviderWeightInfo};
use pallet_prelude::*;

/// Weight functions needed for pallet_bitcoin_locks.
pub trait WeightInfo {
	// Core extrinsics
	fn create_receive_address() -> Weight;
	fn request_release() -> Weight;
	fn cosign_release(input_count: u32) -> Weight;

	// Hooks with variance
	fn on_initialize_with_expirations_and_overdue(
		expiring_count: u32,
		overdue_count: u32,
		orphan_expiring_count: u32,
		securitization_hold_expiration_count: u32,
	) -> Weight {
		let mut weight = Self::on_initialize_base();
		if expiring_count > 0 {
			weight = weight.saturating_add(Self::on_initialize_expiring_locks(expiring_count));
		}
		if overdue_count > 0 {
			weight = weight.saturating_add(Self::on_initialize_overdue_releases(overdue_count));
		}
		if orphan_expiring_count > 0 {
			weight = weight
				.saturating_add(Self::on_initialize_orphan_expirations(orphan_expiring_count));
		}
		if securitization_hold_expiration_count > 0 {
			weight = weight.saturating_add(Self::on_initialize_securitization_hold_expirations(
				securitization_hold_expiration_count,
			));
		}
		weight
	}
	fn on_initialize_base() -> Weight;
	fn on_initialize_expiring_locks(n: u32) -> Weight;
	fn on_initialize_overdue_releases(n: u32) -> Weight;
	fn on_initialize_orphan_expirations(n: u32) -> Weight;
	fn on_initialize_securitization_hold_expirations(n: u32) -> Weight;

	// Admin function
	fn admin_modify_minimum_locked_sats() -> Weight;

	// Orphaned Utxo process
	fn request_orphaned_utxo_release() -> Weight;
	fn cosign_orphaned_utxo_release() -> Weight;
	fn resecuritize() -> Weight;
	fn set_flexible() -> Weight;

	fn provider_fission_satoshis() -> Weight;
	fn provider_validate_fission() -> Weight;
	fn provider_calculate_liquidity_promised() -> Weight;
	fn provider_fuse_satoshis() -> Weight;
	// Bitcoin UTXO event handler provider weights
	fn provider_utxo_detected() -> Weight;
	fn provider_spent() -> Weight;
}

type VaultProviderWeights<T> = <<T as Config>::VaultProvider as BitcoinVaultProvider>::Weights;
type FissionsProviderWeights<T> = <<T as Config>::FissionsProvider as BitcoinFissionsProvider<
	<T as frame_system::Config>::AccountId,
	<T as Config>::Balance,
>>::Weights;
/// Placeholder implementation for tests and no-std environments
pub struct SubstrateWeight<T>(PhantomData<T>);

pub struct WithProviderWeights<
	T,
	Base,
	VaultProviderWeight = VaultProviderWeights<T>,
	FissionsProviderWeight = FissionsProviderWeights<T>,
>(PhantomData<(T, Base, VaultProviderWeight, FissionsProviderWeight)>);
impl<T, Base, VaultProviderWeight, FissionsProviderWeight> WeightInfo
	for WithProviderWeights<T, Base, VaultProviderWeight, FissionsProviderWeight>
where
	T: Config,
	Base: WeightInfo,
	VaultProviderWeight: BitcoinVaultProviderWeightInfo,
	FissionsProviderWeight: BitcoinFissionsProviderWeightInfo,
{
	fn create_receive_address() -> Weight {
		Base::create_receive_address()
	}

	fn request_release() -> Weight {
		Base::request_release()
	}

	fn cosign_release(input_count: u32) -> Weight {
		Base::cosign_release(input_count)
			.saturating_add(FissionsProviderWeight::close_for_lock())
	}

	fn on_initialize_base() -> Weight {
		Base::on_initialize_base()
	}

	fn on_initialize_expiring_locks(n: u32) -> Weight {
		Base::on_initialize_expiring_locks(n)
			.saturating_add(FissionsProviderWeight::close_for_lock().saturating_mul(n.into()))
	}

	fn on_initialize_overdue_releases(n: u32) -> Weight {
		Base::on_initialize_overdue_releases(n)
			.saturating_add(FissionsProviderWeight::close_for_lock().saturating_mul(n.into()))
	}

	fn on_initialize_orphan_expirations(n: u32) -> Weight {
		Base::on_initialize_orphan_expirations(n)
	}

	fn on_initialize_securitization_hold_expirations(n: u32) -> Weight {
		Base::on_initialize_securitization_hold_expirations(n)
			.saturating_add(T::DbWeight::get().writes(n.into()))
	}

	fn admin_modify_minimum_locked_sats() -> Weight {
		Base::admin_modify_minimum_locked_sats()
	}

	fn request_orphaned_utxo_release() -> Weight {
		Base::request_orphaned_utxo_release()
	}

	fn cosign_orphaned_utxo_release() -> Weight {
		Base::cosign_orphaned_utxo_release()
	}

	fn resecuritize() -> Weight {
		Base::resecuritize()
			.saturating_add(VaultProviderWeight::resecuritize())
			.saturating_add(FissionsProviderWeight::get_lock_fission_requirements())
	}

	fn set_flexible() -> Weight {
		Base::set_flexible().saturating_add(VaultProviderWeights::<T>::set_bitcoin_lock_flexible())
	}

	fn provider_fission_satoshis() -> Weight {
		Base::provider_fission_satoshis()
			.saturating_add(FissionsProviderWeight::get_lock_fission_requirements())
	}

	fn provider_validate_fission() -> Weight {
		Base::provider_validate_fission()
			.saturating_add(FissionsProviderWeight::get_lock_fission_requirements())
	}

	fn provider_calculate_liquidity_promised() -> Weight {
		Base::provider_calculate_liquidity_promised()
	}

	fn provider_fuse_satoshis() -> Weight {
		Base::provider_fuse_satoshis()
	}

	fn provider_utxo_detected() -> Weight {
		let max_utxos = T::MaxUtxosPerLock::get().into();
		// MaxEncodedLen proof charged by bitcoin_utxos::UtxoRefsByLockId.
		Base::provider_utxo_detected()
			.saturating_add(VaultProviderWeight::burn())
			.saturating_add(FissionsProviderWeight::close_for_lock())
			.saturating_add(T::DbWeight::get().reads_writes(max_utxos, max_utxos))
			.saturating_add(Weight::from_parts(0, 6_093).saturating_mul(max_utxos))
	}

	fn provider_spent() -> Weight {
		Base::provider_spent()
			.saturating_add(VaultProviderWeight::burn())
			.saturating_add(FissionsProviderWeight::close_for_lock())
	}
}

pub struct ProviderWeightAdapter<T>(PhantomData<T>);
impl<T: Config> BitcoinFissionLockProviderWeightInfo for ProviderWeightAdapter<T> {
	fn fission_satoshis() -> Weight {
		<T as Config>::WeightInfo::provider_fission_satoshis()
	}

	fn validate_fission() -> Weight {
		<T as Config>::WeightInfo::provider_validate_fission()
	}

	fn calculate_liquidity_promised() -> Weight {
		<T as Config>::WeightInfo::provider_calculate_liquidity_promised()
	}

	fn fuse_satoshis() -> Weight {
		<T as Config>::WeightInfo::provider_fuse_satoshis()
	}
}
impl<T: Config> BitcoinUtxoEventsWeightInfo for ProviderWeightAdapter<T> {
	fn utxo_detected() -> Weight {
		<T as Config>::WeightInfo::provider_utxo_detected()
	}

	fn spent() -> Weight {
		<T as Config>::WeightInfo::provider_spent()
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_receive_address() -> Weight { Weight::zero() }
	fn request_release() -> Weight { Weight::zero() }
	fn cosign_release(_input_count: u32) -> Weight { Weight::zero() }
	fn on_initialize_base() -> Weight { Weight::zero() }
	fn on_initialize_expiring_locks(_n: u32) -> Weight { Weight::zero() }
	fn on_initialize_overdue_releases(_n: u32) -> Weight { Weight::zero() }
	fn on_initialize_orphan_expirations(_n: u32) -> Weight { Weight::zero() }
	fn on_initialize_securitization_hold_expirations(_n: u32) -> Weight { Weight::zero() }
	fn admin_modify_minimum_locked_sats() -> Weight { Weight::zero() }
	fn request_orphaned_utxo_release() -> Weight { Weight::zero() }
	fn cosign_orphaned_utxo_release() -> Weight { Weight::zero() }
	fn resecuritize() -> Weight { Weight::zero() }
	fn set_flexible() -> Weight { Weight::zero() }
	fn provider_fission_satoshis() -> Weight { Weight::zero() }
	fn provider_validate_fission() -> Weight { Weight::zero() }
	fn provider_calculate_liquidity_promised() -> Weight { Weight::zero() }
	fn provider_fuse_satoshis() -> Weight { Weight::zero() }
	fn provider_utxo_detected() -> Weight { Weight::zero() }
	fn provider_spent() -> Weight { Weight::zero() }
}
