name: Test End to End
'on':
  workflow_dispatch:
    inputs:
      runIdForBindings:
        description: 'The bindings run id to download artifacts from'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    name: Test e2e bindings on linux

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Install client
        run: yarn tsc
        shell: bash
        working-directory: ./client/nodejs

      - name: Docker Internal Host
        run: |
          echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts

      - name: Pull Miner
        run: docker pull ghcr.io/argonprotocol/argon-miner:dev && docker pull ghcr.io/argonprotocol/argon-notary:dev

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-unknown-linux-gnu
          path: localchain
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.inputs.runIdForBindings }}

      - name: Test bindings
        run: yarn test:js-only --forceExit --verbose --runInBand
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_DOCKER_HOST: true
          DEBUG: "*"
