name: Test End to End
'on':
  workflow_dispatch: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    name: Test bindings on ${{ matrix.target }} - node@${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
        node: 18

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Install client
        run: yarn tsc
        shell: bash
        working-directory: ./client/nodejs

      - name: Docker Internal Host
        run: |
          echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts

      - name: Pull Miner
        run: docker pull ghcr.io/ulixee/ulixee-miner:dev && docker pull ghcr.io/ulixee/ulixee-notary:dev

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.target }}
          path: localchain
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 9930963054

      - name: Test bindings
        run: yarn test:js-only --testTimeout=30000 --forceExit --verbose --runInBand
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_DOCKER_HOST: true
